const falseBoolean = { type: "boolean", enum: [false] };

const analyticsAuthzChecks = [
  "admin_csv_export_readback",
  "admin_summary_readback",
  "analytics_evidence_redaction_reviewed",
  "analytics_log_redaction",
  "cross_org_summary_denied",
  "cross_workspace_export_scoped",
  "csv_export_hash_recorded",
  "eval_evidence_resource_grant_enforced",
  "non_admin_csv_denied",
  "non_admin_summary_denied",
  "raw_analytics_content_absent",
  "usage_scope_enforced",
] as const;

const analyticsAuthzWarnings = [
  "analytics_authz_admin_readback_missing",
  "analytics_authz_cross_org_denial_missing",
  "analytics_authz_cross_workspace_scoping_missing",
  "analytics_authz_csv_export_missing",
  "analytics_authz_csv_hash_missing",
  "analytics_authz_eval_grant_missing",
  "analytics_authz_evidence_failed",
  "analytics_authz_evidence_invalid",
  "analytics_authz_evidence_not_configured",
  "analytics_authz_evidence_not_live",
  "analytics_authz_evidence_not_passed",
  "analytics_authz_live_authorization_missing",
  "analytics_authz_live_deployment_invalid",
  "analytics_authz_live_failure_codes_present",
  "analytics_authz_live_readback_missing",
  "analytics_authz_live_subjects_missing",
  "analytics_authz_non_admin_denial_missing",
  "analytics_authz_redaction_missing",
  "analytics_authz_required_checks_missing",
  "analytics_authz_usage_scope_missing",
] as const;

export const analyticsAuthzPostureSchemas = {
  AnalyticsAuthzPostureReport: {
    type: "object",
    required: [
      "schema",
      "generatedAt",
      "orgId",
      "status",
      "evidence",
      "checks",
      "subjects",
      "authorization",
      "analytics",
      "redaction",
      "warnings",
    ],
    additionalProperties: false,
    properties: {
      schema: { type: "string", enum: ["romeo.analytics-authz-posture.v1"] },
      generatedAt: { type: "string", format: "date-time" },
      orgId: { type: "string" },
      status: { type: "string", enum: ["attention_required", "ready"] },
      evidence: {
        type: "object",
        required: ["configured", "source", "status", "failureCodes"],
        additionalProperties: false,
        properties: {
          configured: { type: "boolean" },
          source: {
            type: "string",
            enum: ["configured_file", "not_configured"],
          },
          status: {
            type: "string",
            enum: [
              "failed",
              "invalid",
              "not_configured",
              "planned",
              "satisfied",
            ],
          },
          schemaVersion: {
            type: "string",
            enum: ["romeo.analytics-authz-live-evidence.v1"],
          },
          generatedAt: { type: "string", format: "date-time" },
          evidenceStatus: {
            type: "string",
            enum: ["failed", "passed", "planned", "unknown"],
          },
          mode: { type: "string", enum: ["dry-run", "live", "unknown"] },
          deployment: {
            type: "string",
            enum: ["compose", "kubernetes", "target", "unknown"],
          },
          invalidReason: {
            type: "string",
            enum: ["invalid_json", "read_failed", "schema_mismatch"],
          },
          failureCodes: { type: "array", items: { type: "string" } },
        },
      },
      checks: {
        type: "object",
        required: [
          "total",
          "requiredTotal",
          "requiredPresent",
          "missingRequired",
        ],
        additionalProperties: false,
        properties: {
          total: { type: "integer", minimum: 0 },
          requiredTotal: { type: "integer", minimum: 0 },
          requiredPresent: { type: "integer", minimum: 0 },
          missingRequired: {
            type: "array",
            items: { type: "string", enum: [...analyticsAuthzChecks] },
          },
        },
      },
      subjects: integerObject([
        "adminSubjectCount",
        "orgAdminSubjectCount",
        "nonAdminSubjectCount",
        "serviceAccountSubjectCount",
        "crossOrgSubjectCount",
      ]),
      authorization: integerObject([
        "adminSummaryAllowedCount",
        "adminCsvAllowedCount",
        "nonAdminSummaryDeniedCount",
        "nonAdminCsvDeniedCount",
        "missingUsageScopeDeniedCount",
        "evalGrantDeniedCount",
        "crossOrgDeniedCount",
        "crossWorkspaceScopedCount",
      ]),
      analytics: integerObject([
        "summaryReadCount",
        "csvExportReadCount",
        "evalEvidenceReadCount",
        "csvSha256Count",
        "usageMetricCount",
        "evalSuiteCount",
        "jobSummaryCount",
        "providerSummaryCount",
      ]),
      redaction: {
        type: "object",
        required: [
          "apiKeysReturned",
          "evidenceFileBodiesReturned",
          "rawAnalyticsCsvRowsReturned",
          "rawEvalInputsReturned",
          "rawEvalOutputsReturned",
          "rawEvidencePathsReturned",
          "rawHumanRatingCommentsReturned",
          "rawJobPayloadsReturned",
          "rawOrgNamesReturned",
          "rawProviderConfigReturned",
          "rawSecretRefsReturned",
          "rawToolInputsReturned",
          "rawUsageMetadataReturned",
          "rawUserEmailsReturned",
          "rawWorkspaceNamesReturned",
          "secretValuesReturned",
          "tokenValuesReturned",
        ],
        additionalProperties: false,
        properties: {
          apiKeysReturned: falseBoolean,
          evidenceFileBodiesReturned: falseBoolean,
          rawAnalyticsCsvRowsReturned: falseBoolean,
          rawEvalInputsReturned: falseBoolean,
          rawEvalOutputsReturned: falseBoolean,
          rawEvidencePathsReturned: falseBoolean,
          rawHumanRatingCommentsReturned: falseBoolean,
          rawJobPayloadsReturned: falseBoolean,
          rawOrgNamesReturned: falseBoolean,
          rawProviderConfigReturned: falseBoolean,
          rawSecretRefsReturned: falseBoolean,
          rawToolInputsReturned: falseBoolean,
          rawUsageMetadataReturned: falseBoolean,
          rawUserEmailsReturned: falseBoolean,
          rawWorkspaceNamesReturned: falseBoolean,
          secretValuesReturned: falseBoolean,
          tokenValuesReturned: falseBoolean,
        },
      },
      warnings: {
        type: "array",
        items: { type: "string", enum: [...analyticsAuthzWarnings] },
      },
    },
  },
};

function integerObject(keys: string[]) {
  return {
    type: "object",
    required: keys,
    additionalProperties: false,
    properties: Object.fromEntries(
      keys.map((key) => [key, { type: "integer", minimum: 0 }]),
    ),
  };
}
