const falseBoolean = { type: "boolean", enum: [false] };
const nonNegativeInteger = { type: "integer", minimum: 0 };

const voiceProviderLiveChecks = [
  "live_tts_preview_verified",
  "live_transcription_verified",
  "voice_artifact_readback_verified",
  "voice_artifact_deletion_verified",
  "streaming_consent_reviewed",
  "provider_failure_redaction_verified",
  "voice_log_redaction",
  "voice_evidence_redaction_reviewed",
] as const;

const voiceProviderLiveWarnings = [
  "voice_provider_live_artifact_missing",
  "voice_provider_live_evidence_failed",
  "voice_provider_live_evidence_invalid",
  "voice_provider_live_evidence_not_configured",
  "voice_provider_live_evidence_not_live",
  "voice_provider_live_evidence_not_passed",
  "voice_provider_live_deployment_invalid",
  "voice_provider_live_failure_redaction_missing",
  "voice_provider_live_log_redaction_missing",
  "voice_provider_live_provider_credential_missing",
  "voice_provider_live_provider_runtime_disabled",
  "voice_provider_live_redaction_missing",
  "voice_provider_live_required_checks_missing",
  "voice_provider_live_streaming_consent_missing",
  "voice_provider_live_transcription_missing",
  "voice_provider_live_tts_missing",
] as const;

export const voiceProviderLivePostureSchemas = {
  VoiceProviderLivePostureReport: {
    type: "object",
    required: [
      "schema",
      "generatedAt",
      "orgId",
      "status",
      "runtime",
      "evidence",
      "checks",
      "provider",
      "tts",
      "transcription",
      "artifacts",
      "streamingConsent",
      "logRedaction",
      "redaction",
      "warnings",
    ],
    additionalProperties: false,
    properties: {
      schema: {
        type: "string",
        enum: ["romeo.voice-provider-live-posture.v1"],
      },
      generatedAt: { type: "string", format: "date-time" },
      orgId: { type: "string" },
      status: { type: "string", enum: ["attention_required", "ready"] },
      runtime: {
        type: "object",
        required: [
          "catalogVoiceCount",
          "liveEvidencePathConfigured",
          "providerCredentialConfigured",
          "providerDriver",
          "transcriptionModelConfigured",
          "ttsModelConfigured",
        ],
        additionalProperties: false,
        properties: {
          catalogVoiceCount: nonNegativeInteger,
          liveEvidencePathConfigured: { type: "boolean" },
          providerCredentialConfigured: { type: "boolean" },
          providerDriver: {
            type: "string",
            enum: ["disabled", "dev", "openai-compatible"],
          },
          transcriptionModelConfigured: { type: "boolean" },
          ttsModelConfigured: { type: "boolean" },
        },
      },
      evidence: {
        type: "object",
        required: ["configured", "source", "status", "failureCodes"],
        additionalProperties: false,
        properties: {
          configured: { type: "boolean" },
          source: {
            type: "string",
            enum: ["configured_file", "not_configured"],
          },
          status: {
            type: "string",
            enum: [
              "failed",
              "invalid",
              "not_configured",
              "planned",
              "satisfied",
            ],
          },
          schemaVersion: {
            type: "string",
            enum: ["romeo.voice-provider-live-evidence.v1"],
          },
          generatedAt: { type: "string", format: "date-time" },
          evidenceStatus: {
            type: "string",
            enum: ["failed", "passed", "planned", "unknown"],
          },
          mode: { type: "string", enum: ["dry-run", "live", "unknown"] },
          deployment: {
            type: "string",
            enum: ["compose", "kubernetes", "target", "unknown"],
          },
          invalidReason: {
            type: "string",
            enum: ["invalid_json", "read_failed", "schema_mismatch"],
          },
          failureCodes: { type: "array", items: { type: "string" } },
        },
      },
      checks: {
        type: "object",
        required: [
          "total",
          "requiredTotal",
          "requiredPresent",
          "missingRequired",
        ],
        additionalProperties: false,
        properties: {
          total: nonNegativeInteger,
          requiredTotal: nonNegativeInteger,
          requiredPresent: nonNegativeInteger,
          missingRequired: {
            type: "array",
            items: { type: "string", enum: [...voiceProviderLiveChecks] },
          },
        },
      },
      provider: {
        type: "object",
        required: [
          "driver",
          "catalogSyncCount",
          "configuredVoiceCount",
          "providerFailureRedacted",
          "transcriptionRequestCount",
          "ttsRequestCount",
        ],
        additionalProperties: false,
        properties: {
          driver: {
            type: "string",
            enum: ["dev", "disabled", "openai-compatible", "unknown"],
          },
          catalogSyncCount: nonNegativeInteger,
          configuredVoiceCount: nonNegativeInteger,
          providerFailureRedacted: { type: "boolean" },
          transcriptionRequestCount: nonNegativeInteger,
          ttsRequestCount: nonNegativeInteger,
        },
      },
      tts: {
        type: "object",
        required: [
          "livePreviewVerified",
          "generatedArtifactCount",
          "generatedAudioBytes",
        ],
        additionalProperties: false,
        properties: {
          livePreviewVerified: { type: "boolean" },
          generatedArtifactCount: nonNegativeInteger,
          generatedAudioBytes: nonNegativeInteger,
        },
      },
      transcription: {
        type: "object",
        required: [
          "liveTranscriptionVerified",
          "audioBytes",
          "promptProvided",
          "transcriptLength",
        ],
        additionalProperties: false,
        properties: {
          liveTranscriptionVerified: { type: "boolean" },
          audioBytes: nonNegativeInteger,
          promptProvided: { type: "boolean" },
          transcriptLength: nonNegativeInteger,
        },
      },
      artifacts: {
        type: "object",
        required: [
          "readbackVerified",
          "readbackBytes",
          "deleteVerified",
          "deletedArtifactCount",
        ],
        additionalProperties: false,
        properties: {
          readbackVerified: { type: "boolean" },
          readbackBytes: nonNegativeInteger,
          deleteVerified: { type: "boolean" },
          deletedArtifactCount: nonNegativeInteger,
        },
      },
      streamingConsent: {
        type: "object",
        required: ["streamingEnabled", "reviewed", "reviewedPolicyCount"],
        additionalProperties: false,
        properties: {
          streamingEnabled: { type: "boolean" },
          reviewed: { type: "boolean" },
          reviewedPolicyCount: nonNegativeInteger,
        },
      },
      logRedaction: {
        type: "object",
        required: [
          "appLogRedactionVerified",
          "podLogRedactionVerified",
          "appLogScanCount",
          "podLogScanCount",
          "rawAudioSentinelHitCount",
          "rawSpeechTextSentinelHitCount",
          "rawTranscriptSentinelHitCount",
          "secretSentinelHitCount",
        ],
        additionalProperties: false,
        properties: {
          appLogRedactionVerified: { type: "boolean" },
          podLogRedactionVerified: { type: "boolean" },
          appLogScanCount: nonNegativeInteger,
          podLogScanCount: nonNegativeInteger,
          rawAudioSentinelHitCount: nonNegativeInteger,
          rawSpeechTextSentinelHitCount: nonNegativeInteger,
          rawTranscriptSentinelHitCount: nonNegativeInteger,
          secretSentinelHitCount: nonNegativeInteger,
        },
      },
      redaction: {
        type: "object",
        required: [
          "evidenceFileBodyReturned",
          "rawAudioReturned",
          "rawEvidencePathsReturned",
          "rawObjectStoreKeysReturned",
          "rawProviderEndpointReturned",
          "rawProviderResponseReturned",
          "rawSpeechTextReturned",
          "rawTranscriptTextReturned",
          "secretValuesReturned",
          "tokenValuesReturned",
        ],
        additionalProperties: false,
        properties: {
          evidenceFileBodyReturned: falseBoolean,
          rawAudioReturned: falseBoolean,
          rawEvidencePathsReturned: falseBoolean,
          rawObjectStoreKeysReturned: falseBoolean,
          rawProviderEndpointReturned: falseBoolean,
          rawProviderResponseReturned: falseBoolean,
          rawSpeechTextReturned: falseBoolean,
          rawTranscriptTextReturned: falseBoolean,
          secretValuesReturned: falseBoolean,
          tokenValuesReturned: falseBoolean,
        },
      },
      warnings: {
        type: "array",
        items: { type: "string", enum: [...voiceProviderLiveWarnings] },
      },
    },
  },
};
