import type { AuthSubject } from "./types";

export const seededSubject: AuthSubject = {
  id: "user_dev_admin",
  type: "user",
  email: "admin@romeo.local",
  name: "Romeo Admin",
  orgId: "org_default",
  workspaceIds: ["workspace_default"],
  groupIds: ["group_admins"],
  scopes: [
    "me:read",
    "organizations:read",
    "workspaces:read",
    "providers:read",
    "providers:write",
    "models:read",
    "models:use",
    "agents:read",
    "agents:create",
    "agents:write",
    "agents:run",
    "chats:read",
    "chats:write",
    "runs:read",
    "runs:create",
    "runs:cancel",
    "files:read",
    "files:write",
    "knowledge:read",
    "knowledge:write",
    "knowledge:query",
    "audit:read",
    "usage:read",
    "webhooks:read",
    "webhooks:write",
    "voices:use",
    "voices:manage",
    "tools:use",
    "tools:manage",
    "admin:read",
    "admin:write",
  ],
  isAdmin: true,
  adminRole: "global_admin",
};
