export {
  AwsSecretsManagerResolver,
  AzureKeyVaultResolver,
  CloudSecretResolver,
  GcpSecretManagerResolver,
  type AwsSecretsManagerResolverOptions,
  type AwsSecretsManagerSdkClient,
  type AwsSecretsManagerSdkClientFactory,
  type AzureKeyVaultResolverOptions,
  type AzureKeyVaultSdkClient,
  type AzureKeyVaultSdkClientFactory,
  type GcpSecretManagerResolverOptions,
  type GcpSecretManagerSdkClient,
  type GcpSecretManagerSdkClientFactory,
} from "@romeo/secrets";
