import type { RomeoEnv } from "@romeo/config";
import type { ObjectStore } from "@romeo/storage";
import type { VoiceProvider } from "@romeo/voices";

import type { AbuseControlService } from "./abuse-control-service";
import type { AgentKnowledgeService } from "./agent-knowledge-service";
import type { AgentService } from "./agent-service";
import type { AnalyticsService } from "./analytics-service";
import type { ApiKeyService } from "./api-key-service";
import type { AuditService } from "./audit-service";
import type { AuthProviderSettingsService } from "./auth-provider-settings-service";
import type { BillingService } from "./billing-service";
import type { BrowserAutomationService } from "./browser-automation-service";
import type { ChannelService } from "./channel-service";
import type { CapabilityService } from "./capability-resolver";
import type { OrganizationCapabilityFlagService } from "./organization-capability-flag-service";
import type { ChatCommentService } from "./chat-comment-service";
import type { ChatEventService } from "./chat-event-service";
import type { ChatEventTransport } from "./chat-event-transport";
import type { ChatExperienceService } from "./chat-experience-service";
import type { ChatService } from "./chat-service";
import type { ChatTagService } from "./chat-tag-service";
import type { CollaborationService } from "./collaboration-service";
import type { ContentPolicyService } from "./content-policy-service";
import type { ContentPolicyVersionService } from "./content-policy-version-service";
import type { PolicyApprovalService } from "./policy-approval-service";
import type { DataConnectorExecutor } from "./data-connector-executors";
import type { DataConnectorService } from "./data-connector-service";
import type { DelegatedOAuthService } from "./delegated-oauth-service";
import type { DeviceAuthorizationService } from "./device-authorization-service";
import type { DirectorySyncService } from "./directory-sync-service";
import type { EdgeSecurityService } from "./edge-security-service";
import type { EvalService } from "./eval-service";
import type { FileOcrProvider } from "./file-ocr";
import type { FileMalwareScanner, FileService } from "./file-service";
import type { GaEvidencePostureService } from "./ga-evidence-posture-service";
import type { GovernanceService } from "./governance-service";
import type { GroupService } from "./group-service";
import type { ImageGenerationService } from "./image-generation-service";
import type { ImageJobStore } from "./image-job-store";
import type { ModelCapabilityProbeService } from "./model-capability-probe";
import type { InterfacePreferenceService } from "./interface-preference-service";
import type { IdempotencyService } from "./idempotency-service";
import type { JobService } from "./job-service";
import type { KnowledgeBinaryExtractor } from "./knowledge-extraction-worker";
import type { KnowledgeService } from "./knowledge-service";
import type { LdapClientFactory } from "./ldap-directory-client";
import type { LdapAuthService } from "./ldap-auth-service";
import type { LocalAuthService } from "./local-auth-service";
import type { ManagedSecretService } from "./managed-secret-service";
import type {
  ResendEmailClientFactory,
  SmtpSendMail,
} from "./notification-delivery";
import type { FcmMessagingClientFactory } from "./notification-delivery-mobile";
import type { NotificationService } from "./notification-service";
import type { OAuth2PkceService } from "./oauth2-pkce-service";
import type { OidcAuthenticator } from "./oidc-auth-service";
import type { OidcPkceService } from "./oidc-pkce-service";
import type { OpenAiChatCompletionsService } from "./openai-chat-completions-service";
import type { OpenAiEmbeddingsService } from "./openai-embeddings-service";
import type { OpenAiModelsService } from "./openai-models-service";
import type { OpenWebUiCompatibilityService } from "./openwebui-compatibility-service";
import type { PostgresOperationalPostureService } from "./postgres-operational-posture-service";
import type { PromptTemplateService } from "./prompt-template-service";
import type { ProviderService } from "./provider-service";
import type { ProviderCapabilityReportService } from "./provider-capability-report-service";
import type { QdrantSdkClientFactory } from "./qdrant-knowledge-vector-store";
import type { QuotaCoordinator } from "./quota-coordination";
import type { QuotaService } from "./quota-service";
import type { RagPolicyService } from "./rag-policy-service";
import type { RagPostureService } from "./rag-posture-service";
import type { ReadinessService } from "./readiness-service";
import type { RunService } from "./run-service";
import type { RunEventTransport } from "./run-event-transport";
import type { SamlClientFactory } from "./saml-client";
import type { SamlAuthService } from "./saml-auth-service";
import type { ScimService } from "./scim-service";
import type { SecretResolver } from "./secret-resolver";
import type { SecretRotationService } from "./secret-rotation-service";
import type { SecretWriter } from "./secret-writer";
import type { ServiceAccountService } from "./service-account-service";
import type { SessionService } from "./session-service";
import type { SsoSettingsService } from "./sso-settings-service";
import type { TemporaryChatCleanupWorker } from "./temporary-chat-cleanup-worker";
import type { TenantAdminService } from "./tenant-admin-service";
import type { ToolConnectorService } from "./tool-connector-service";
import type { ToolService } from "./tool-service";
import type { InventoriedTablePageService } from "./inventoried-table-page-service";
import type { ServerTableExportWorker } from "./server-table-export-worker";
import type { ServerTableViewService } from "./server-table-view-service";
import type { UsageService } from "./usage-service";
import type { UserLifecycleService } from "./user-lifecycle-service";
import type { VoiceService } from "./voice-service";
import type { WebhookService } from "./webhook-service";
import type { WebSearchService } from "./web-search-service";
import type { WorkflowService } from "./workflow-service";
import type { WorkspaceContentService } from "./workspace-content-service";
import type { WorkspaceService } from "./workspace-service";

export interface RomeoServices {
  abuseControls: AbuseControlService;
  analytics: AnalyticsService;
  agentKnowledge: AgentKnowledgeService;
  agents: AgentService;
  apiKeys: ApiKeyService;
  audit: AuditService;
  authProviderSettings: AuthProviderSettingsService;
  billing: BillingService;
  browserAutomation: BrowserAutomationService;
  channels: ChannelService;
  capabilities: CapabilityService;
  capabilityFlags: OrganizationCapabilityFlagService;
  chatEvents: ChatEventService;
  chatExperience: ChatExperienceService;
  chats: ChatService;
  temporaryChatCleanup: TemporaryChatCleanupWorker;
  chatComments: ChatCommentService;
  chatTags: ChatTagService;
  collaboration: CollaborationService;
  contentPolicy: ContentPolicyService;
  contentPolicyVersions: ContentPolicyVersionService;
  contentPolicyApprovals: PolicyApprovalService;
  dataConnectors: DataConnectorService;
  delegatedOAuth: DelegatedOAuthService;
  deployment: { tenancyMode: RomeoEnv["TENANCY_MODE"] };
  directorySync: DirectorySyncService;
  deviceAuthorizations: DeviceAuthorizationService;
  edgeSecurity: EdgeSecurityService;
  evals: EvalService;
  files: FileService;
  gaEvidencePosture: GaEvidencePostureService;
  knowledge: KnowledgeService;
  jobs: JobService;
  images: ImageGenerationService;
  imageJobs: ImageJobStore;
  modelCapabilityProbes: ModelCapabilityProbeService;
  interfacePreferences: InterfacePreferenceService;
  idempotency: IdempotencyService;
  ldapAuth: LdapAuthService;
  localAuth: LocalAuthService;
  managedSecrets: ManagedSecretService;
  governance: GovernanceService;
  groups: GroupService;
  notifications: NotificationService;
  oidc: OidcAuthenticator;
  oidcPkce: OidcPkceService;
  oauth2Pkce: OAuth2PkceService;
  openAiChatCompletions: OpenAiChatCompletionsService;
  openAiEmbeddings: OpenAiEmbeddingsService;
  openAiModels: OpenAiModelsService;
  openWebUiCompatibility: OpenWebUiCompatibilityService;
  postgresOperationalPosture: PostgresOperationalPostureService;
  providers: ProviderService;
  providerCapabilityReports: ProviderCapabilityReportService;
  prompts: PromptTemplateService;
  quotas: QuotaService;
  ragPolicy: RagPolicyService;
  ragPosture: RagPostureService;
  readiness: ReadinessService;
  runs: RunService;
  samlAuth: SamlAuthService;
  scim: ScimService;
  secretRotation: SecretRotationService;
  serviceAccounts: ServiceAccountService;
  sessions: SessionService;
  ssoSettings: SsoSettingsService;
  tenantAdmin: TenantAdminService;
  toolConnectors: ToolConnectorService;
  tools: ToolService;
  tableExports: ServerTableExportWorker;
  tablePages: InventoriedTablePageService;
  tableViews: ServerTableViewService;
  usage: UsageService;
  users: UserLifecycleService;
  voices: VoiceService;
  webhooks: WebhookService;
  webSearch: WebSearchService;
  workflows: WorkflowService;
  workspace: WorkspaceService;
  workspaceContent: WorkspaceContentService;
}

export interface CreateServicesOptions {
  env?: RomeoEnv;
  dataConnectorExecutor?: DataConnectorExecutor;
  knowledgeExtractor?: KnowledgeBinaryExtractor;
  embeddingFetch?: typeof fetch;
  fileMalwareScanner?: FileMalwareScanner;
  fileOcrProvider?: FileOcrProvider;
  delegatedOAuthFetch?: typeof fetch;
  ldapClientFactory?: LdapClientFactory;
  objectStore?: ObjectStore;
  oidcFetch?: typeof fetch;
  providerFetch?: typeof fetch;
  qdrantClientFactory?: QdrantSdkClientFactory;
  quotaCoordinator?: QuotaCoordinator;
  chatEventTransport?: ChatEventTransport;
  runEventTransport?: RunEventTransport;
  samlClientFactory?: SamlClientFactory;
  secretResolver?: SecretResolver;
  secretWriter?: SecretWriter;
  notificationSmtpSendMail?: SmtpSendMail;
  notificationResendClientFactory?: ResendEmailClientFactory;
  notificationFcmClientFactory?: FcmMessagingClientFactory;
  toolOperationFetch?: typeof fetch;
  voiceProvider?: VoiceProvider;
  webhookFetch?: typeof fetch;
}
