import {
  addGroupMemberRoute,
  bulkDisableServiceAccountsRoute,
  bulkRevokeApiKeysRoute,
  createApiKeyRoute,
  createGroupRoute,
  createServiceAccountApiKeyRoute,
  createServiceAccountRoute,
  directorySyncRoute,
  disableServiceAccountRoute,
  disableUserRoute,
  listApiKeysRoute,
  listGroupMembersRoute,
  listGroupsRoute,
  listServiceAccountsRoute,
  listUsersRoute,
  removeGroupMemberRoute,
  revokeApiKeyRoute,
  setUserLocalPasswordRoute,
  updateUserRoleRoute,
} from "./administration";

export const administrationRoutes = [
  listUsersRoute,
  disableUserRoute,
  updateUserRoleRoute,
  setUserLocalPasswordRoute,
  directorySyncRoute,
  listGroupsRoute,
  createGroupRoute,
  listGroupMembersRoute,
  addGroupMemberRoute,
  removeGroupMemberRoute,
  listApiKeysRoute,
  createApiKeyRoute,
  bulkRevokeApiKeysRoute,
  revokeApiKeyRoute,
  listServiceAccountsRoute,
  createServiceAccountRoute,
  bulkDisableServiceAccountsRoute,
  createServiceAccountApiKeyRoute,
  disableServiceAccountRoute,
] as const;
