import {
  addFolderItemRoute,
  assignChatTagRoute,
  createFavoriteRoute,
  createFolderRoute,
  deleteFavoriteRoute,
  deleteFolderItemRoute,
  deleteFolderRoute,
  getFolderRoute,
  listChatSharesRoute,
  listChatTagAssignmentsRoute,
  listChatTagsRoute,
  listChatsForTagRoute,
  listFavoritesRoute,
  listFileSharesRoute,
  listFolderItemsRoute,
  listFolderSharesRoute,
  listFoldersRoute,
  listKnowledgeBaseSharesRoute,
  listShareTargetsRoute,
  removeChatTagRoute,
  revokeChatShareRoute,
  shareChatRoute,
  shareFileRoute,
  shareFolderRoute,
  shareKnowledgeBaseRoute,
  updateFolderRoute,
} from "./collaboration";

export const collaborationRoutes = [
  listShareTargetsRoute,
  listKnowledgeBaseSharesRoute,
  shareKnowledgeBaseRoute,
  listChatSharesRoute,
  shareChatRoute,
  revokeChatShareRoute,
  listFileSharesRoute,
  shareFileRoute,
  listFavoritesRoute,
  createFavoriteRoute,
  deleteFavoriteRoute,
  listFoldersRoute,
  createFolderRoute,
  getFolderRoute,
  updateFolderRoute,
  deleteFolderRoute,
  listFolderSharesRoute,
  shareFolderRoute,
  listFolderItemsRoute,
  addFolderItemRoute,
  deleteFolderItemRoute,
  listChatTagsRoute,
  listChatsForTagRoute,
  listChatTagAssignmentsRoute,
  assignChatTagRoute,
  removeChatTagRoute,
] as const;
