import { z } from "@hono/zod-openapi";

import {
  GaEvidencePostureGateSchema,
  evidenceInvalidReason,
  gaBundleTarget,
  gaSummary,
  gaTarget,
  id,
  preflightGate,
  targetExecutionGate,
  targetPlanGate,
  timestamp,
} from "./ga-evidence-posture-base";

export const GaEvidencePostureReportSchema = z
  .strictObject({
    schema: z.literal("romeo.ga-evidence-posture.v1"),
    generatedAt: timestamp,
    orgId: id,
    status: z.enum(["attention_required", "passed"]),
    checklist: z.strictObject({
      configured: z.boolean(),
      source: z.enum(["configured_file", "not_configured"]),
      status: z.enum(["blocked", "invalid", "not_configured", "passed"]),
      schemaVersion: z.string().optional(),
      generatedAt: timestamp.optional(),
      strict: z.boolean().optional(),
      target: gaTarget.optional(),
      summary: gaSummary,
      exceptionCount: z.number().int().nonnegative(),
      invalidReason: evidenceInvalidReason.optional(),
    }),
    targetPreflight: z.strictObject({
      configured: z.boolean(),
      source: z.enum(["configured_file", "not_configured"]),
      status: z.enum(["blocked", "invalid", "not_configured", "ready"]),
      schemaVersion: z.string().optional(),
      generatedAt: timestamp.optional(),
      checklist: z
        .strictObject({
          status: z.string(),
          schemaVersion: z.string().optional(),
          summary: gaSummary,
        })
        .optional(),
      summary: z.strictObject({
        total: z.number().int().nonnegative(),
        ready: z.number().int().nonnegative(),
        blocked: z.number().int().nonnegative(),
        securityCriticalBlocked: z.number().int().nonnegative(),
      }),
      gates: z.array(preflightGate),
      invalidReason: evidenceInvalidReason.optional(),
    }),
    targetPlan: z.strictObject({
      configured: z.boolean(),
      source: z.enum(["configured_file", "not_configured"]),
      status: z.enum(["blocked", "invalid", "not_configured", "ready"]),
      schemaVersion: z.string().optional(),
      generatedAt: timestamp.optional(),
      sourcePreflight: z
        .strictObject({
          schemaVersion: z.string().optional(),
          status: z.string(),
          checklist: z
            .strictObject({
              status: z.string(),
              schemaVersion: z.string().optional(),
              summary: gaSummary,
            })
            .optional(),
        })
        .optional(),
      summary: z.strictObject({
        total: z.number().int().nonnegative(),
        ready: z.number().int().nonnegative(),
        blocked: z.number().int().nonnegative(),
        environmentRequired: z.number().int().nonnegative(),
        securityCriticalBlocked: z.number().int().nonnegative(),
        phaseCount: z.number().int().nonnegative(),
        commandCount: z.number().int().nonnegative(),
        evidenceTargetCount: z.number().int().nonnegative(),
        blockedCheckCount: z.number().int().nonnegative(),
      }),
      phases: z.array(
        z.strictObject({
          phase: z.string(),
          status: z.enum(["blocked", "ready", "unknown"]),
          total: z.number().int().nonnegative(),
          ready: z.number().int().nonnegative(),
          blocked: z.number().int().nonnegative(),
          securityCriticalBlocked: z.number().int().nonnegative(),
          gateIds: z.array(z.string()),
        }),
      ),
      gates: z.array(targetPlanGate),
      invalidReason: evidenceInvalidReason.optional(),
    }),
    targetExecution: z.strictObject({
      configured: z.boolean(),
      source: z.enum(["configured_file", "not_configured"]),
      status: z.enum([
        "blocked",
        "failed",
        "invalid",
        "not_configured",
        "not_run",
        "partial",
        "passed",
      ]),
      schemaVersion: z.string().optional(),
      generatedAt: timestamp.optional(),
      sourcePlan: z
        .strictObject({
          schemaVersion: z.string().optional(),
          status: z.string(),
          checklist: z
            .strictObject({
              status: z.string(),
              schemaVersion: z.string().optional(),
              summary: gaSummary,
            })
            .optional(),
        })
        .optional(),
      execution: z.strictObject({
        confirmed: z.boolean(),
        continueOnFailure: z.boolean(),
        timeoutMs: z.number().int().nonnegative(),
        selectedGateCount: z.number().int().nonnegative(),
        commandsExecuted: z.number().int().nonnegative(),
      }),
      envFile: z.strictObject({
        configured: z.boolean(),
        loaded: z.boolean(),
        variableCount: z.number().int().nonnegative(),
        populatedVariableCount: z.number().int().nonnegative(),
        blankVariableCount: z.number().int().nonnegative(),
        duplicateCount: z.number().int().nonnegative(),
        appliedVariableCount: z.number().int().nonnegative(),
        variableNames: z.array(z.string()),
        warningCodes: z.array(z.string()),
        rawValuesReturned: z.literal(false),
        rawFileBodyReturned: z.literal(false),
        shellSourced: z.literal(false),
        blankValuesApplied: z.literal(false),
      }),
      summary: z.strictObject({
        total: z.number().int().nonnegative(),
        readyToRun: z.number().int().nonnegative(),
        executed: z.number().int().nonnegative(),
        passed: z.number().int().nonnegative(),
        failed: z.number().int().nonnegative(),
        skipped: z.number().int().nonnegative(),
        confirmationRequired: z.number().int().nonnegative(),
        blocked: z.number().int().nonnegative(),
        redacted: z.number().int().nonnegative(),
        commandMissing: z.number().int().nonnegative(),
      }),
      gates: z.array(targetExecutionGate),
      invalidReason: evidenceInvalidReason.optional(),
    }),
    bundle: z.strictObject({
      configured: z.boolean(),
      source: z.enum(["configured_file", "not_configured"]),
      status: z.enum(["blocked", "invalid", "not_configured", "passed"]),
      schemaVersion: z.string().optional(),
      generatedAt: timestamp.optional(),
      requirements: z.strictObject({
        checklistPassed: z.boolean(),
        readbackValidation: z.boolean(),
        supportBundle: z.boolean(),
        supportRedaction: z.boolean(),
        docsCommandCheck: z.boolean(),
        tenantIsolation: z.boolean(),
      }),
      release: z
        .strictObject({
          name: z.string().optional(),
          version: z.string().optional(),
          artifactCount: z.number().int().nonnegative(),
        })
        .optional(),
      ga: gaBundleTarget.optional(),
      inventory: z.strictObject({
        evidenceFileCount: z.number().int().nonnegative(),
        totalBytes: z.number().int().nonnegative(),
        sha256: z.string().optional(),
      }),
      checks: z.strictObject({
        total: z.number().int().nonnegative(),
        passed: z.number().int().nonnegative(),
        failed: z.number().int().nonnegative(),
      }),
      blockerCount: z.number().int().nonnegative(),
      blockerCodes: z.array(z.string()),
      redaction: z.strictObject({
        evidenceBodiesIncluded: z.boolean(),
        exceptionRationaleIncluded: z.boolean(),
        rawEvidencePathsIncluded: z.boolean(),
        rawSecretsIncluded: z.boolean(),
        rawLogsIncluded: z.boolean(),
        rawPromptsIncluded: z.boolean(),
        rawProviderPayloadsIncluded: z.boolean(),
        rawConnectorPayloadsIncluded: z.boolean(),
      }),
      invalidReason: evidenceInvalidReason.optional(),
    }),
    gates: z.array(GaEvidencePostureGateSchema),
    requiredLiveBlockers: z.array(
      z.strictObject({
        id,
        phase: z.string(),
        title: z.string(),
        securityCritical: z.boolean(),
      }),
    ),
    liveGateReadiness: z.array(
      z.strictObject({
        id,
        phase: z.string(),
        title: z.string(),
        securityCritical: z.boolean(),
        checklistStatus: z.enum([
          "blocked",
          "excepted",
          "satisfied",
          "unknown",
        ]),
        preflightStatus: z.enum([
          "blocked",
          "not_configured",
          "ready",
          "unknown",
        ]),
        command: z.string().optional(),
        checklistEvidence: z.strictObject({
          total: z.number().int().nonnegative(),
          satisfied: z.number().int().nonnegative(),
          missing: z.number().int().nonnegative(),
          failed: z.number().int().nonnegative(),
          invalid: z.number().int().nonnegative(),
          unknown: z.number().int().nonnegative(),
        }),
        preflightEvidence: z.strictObject({
          total: z.number().int().nonnegative(),
          ready: z.number().int().nonnegative(),
          missing: z.number().int().nonnegative(),
          blocked: z.number().int().nonnegative(),
          failed: z.number().int().nonnegative(),
          unknown: z.number().int().nonnegative(),
        }),
        checks: z.strictObject({
          total: z.number().int().nonnegative(),
          ready: z.number().int().nonnegative(),
          blocked: z.number().int().nonnegative(),
          optional: z.number().int().nonnegative(),
          unknown: z.number().int().nonnegative(),
          blockedReasons: z.array(z.string()),
        }),
        warnings: z.array(
          z.enum([
            "live_evidence_missing",
            "preflight_blocked",
            "preflight_gate_missing",
            "preflight_not_configured",
          ]),
        ),
      }),
    ),
    redaction: z.strictObject({
      absoluteChecklistPathReturned: z.literal(false),
      absoluteBundlePathReturned: z.literal(false),
      bundleBlockerMessagesReturned: z.literal(false),
      bundleEvidenceFileBodiesReturned: z.literal(false),
      bundleEvidencePathsReturned: z.literal(false),
      evidenceFileBodiesReturned: z.literal(false),
      exceptionApproverReturned: z.literal(false),
      exceptionOwnerReturned: z.literal(false),
      exceptionRationaleReturned: z.literal(false),
      preflightCommandOutputReturned: z.literal(false),
      preflightEnvironmentValuesReturned: z.literal(false),
      preflightFileBodiesReturned: z.literal(false),
      targetPlanCommandOutputReturned: z.literal(false),
      targetPlanEnvironmentValuesReturned: z.literal(false),
      targetPlanEvidenceBodiesReturned: z.literal(false),
      targetExecutionCommandTextReturned: z.literal(false),
      targetExecutionCommandOutputReturned: z.literal(false),
      targetExecutionEnvironmentValuesReturned: z.literal(false),
      targetExecutionEnvFileValuesReturned: z.literal(false),
      targetExecutionEnvFileBodyReturned: z.literal(false),
      targetExecutionEvidenceBodiesReturned: z.literal(false),
      rawEvidencePathsReturned: z.literal(false),
      rawPreflightEvidencePathsReturned: z.literal(false),
      rawTargetPlanEvidencePathsReturned: z.literal(false),
      rawTargetExecutionEvidencePathsReturned: z.literal(false),
    }),
    warnings: z.array(
      z.enum([
        "ga_blocked",
        "ga_bundle_blocked",
        "ga_bundle_invalid",
        "ga_checklist_invalid",
        "ga_checklist_path_not_configured",
        "ga_target_execution_failed",
        "ga_target_execution_invalid",
        "ga_target_plan_invalid",
        "ga_target_preflight_blocked",
        "ga_target_preflight_invalid",
        "live_environment_evidence_required",
      ]),
    ),
  })
  .openapi("GaEvidencePostureReport");
