import { scopeValues } from "@romeo/auth";
import { z } from "@hono/zod-openapi";

import {
  governanceCount as count,
  governanceIdentifier as identifier,
  governanceTimestamp as timestamp,
} from "./governance-schema-primitives";

export const ResourceGrantSchema = z.strictObject({
  id: identifier,
  resourceType: z.enum([
    "organization",
    "workspace",
    "provider",
    "model",
    "agent",
    "chat",
    "run",
    "tool",
    "data_connector",
    "file",
    "knowledge_base",
    "prompt_template",
    "folder",
    "voice_profile",
  ]),
  resourceId: identifier,
  principalType: z.enum(["user", "group", "service_account"]),
  principalId: identifier,
  permission: z.enum(["read", "write", "use", "run"]),
});
export const AccessReviewPolicyPostureSchema = z.strictObject({
  accountLinking: z.literal("disabled"),
  scim: z.enum(["disabled", "enabled"]),
  localAdminSource: z.literal("local"),
  oidcGroupSync: z.literal("additive_known_groups_only"),
  destructiveMembershipSync: z.literal("disabled"),
  supportAccess: z.literal("time_bound_approved_audited"),
});
export const AccessReviewSummarySchema = z.strictObject({
  userCount: count,
  disabledUserCount: count,
  groupCount: count,
  groupMembershipCount: count,
  serviceAccountCount: count,
  disabledServiceAccountCount: count,
  activeUserApiKeyCount: count,
  activeServiceAccountApiKeyCount: count,
  activeUserSessionCount: count,
  resourceGrantCount: count,
  dataConnectorCount: count,
  delegatedOAuthConnectionCount: count,
  toolConnectorCount: count,
  riskyToolConnectorCount: count,
  pendingSupportRequestCount: count,
  activeSupportSessionCount: count,
  runningWorkerJobCount: count,
  queuedWorkerJobCount: count,
});
export const DataConnectorTypeSchema = z.enum([
  "local_import",
  "github",
  "s3",
  "website",
  "rss",
  "confluence",
  "jira",
  "notion",
  "linear",
  "slack",
]);
export const AccessReviewReportSchema = z
  .strictObject({
    schema: z.literal("romeo.access-review-report.v1"),
    orgId: identifier,
    generatedAt: timestamp,
    policy: AccessReviewPolicyPostureSchema,
    summary: AccessReviewSummarySchema,
    users: z.array(
      z.strictObject({
        id: identifier,
        email: z.string().email(),
        name: z.string(),
        disabledAt: timestamp.optional(),
        source: z.enum(["local", "oidc_derived"]),
        groupIds: z.array(identifier),
        activeApiKeyCount: count,
        activeSessionCount: count,
      }),
    ),
    groups: z.array(
      z.strictObject({
        id: identifier,
        name: z.string(),
        slug: z.string(),
        memberCount: count,
        createdAt: timestamp,
      }),
    ),
    serviceAccounts: z.array(
      z.strictObject({
        id: identifier,
        name: z.string(),
        scopes: z.array(z.enum(scopeValues)),
        createdBy: identifier,
        disabledAt: timestamp.optional(),
        activeApiKeyCount: count,
        createdAt: timestamp,
      }),
    ),
    resourceGrants: z.array(ResourceGrantSchema),
    connectorOwnership: z.strictObject({
      dataConnectors: z.array(
        z.strictObject({
          id: identifier,
          workspaceId: identifier,
          knowledgeBaseId: identifier,
          type: DataConnectorTypeSchema,
          status: z.string(),
          createdBy: identifier,
          configKeys: z.array(z.string()),
          sourceAccessMode: z.string().optional(),
          delegatedOAuthConnectionId: identifier.optional(),
          syncIntervalMinutes: count.optional(),
          nextSyncAt: timestamp.optional(),
          lastSyncAt: timestamp.optional(),
          createdAt: timestamp,
          updatedAt: timestamp,
        }),
      ),
      delegatedOAuthConnections: z.array(
        z.strictObject({
          id: identifier,
          workspaceId: identifier,
          userId: identifier,
          providerId: z.literal("github"),
          connectorType: DataConnectorTypeSchema,
          providerAccountLoginConfigured: z.boolean(),
          providerAccountLoginHash: z.string().optional(),
          scopeCount: count,
          status: z.string(),
          accessTokenExpiresAt: timestamp.optional(),
          refreshTokenExpiresAt: timestamp.optional(),
          lastUsedAt: timestamp.optional(),
          revokedAt: timestamp.optional(),
          createdAt: timestamp,
          updatedAt: timestamp,
        }),
      ),
    }),
    toolRisk: z.strictObject({
      connectors: z.array(
        z.strictObject({
          id: identifier,
          type: z.enum([
            "built_in",
            "openapi",
            "mcp",
            "webhook",
            "browser",
            "enterprise",
          ]),
          name: z.string(),
          enabled: z.boolean(),
          riskLevel: z.string(),
          approvalPolicy: z.string(),
          visibility: z.enum(["private", "workspace", "org"]),
          allowedHostCount: count,
          allowPrivateNetwork: z.boolean(),
          operationCount: count,
          enabledOperationCount: count,
          highRiskOperationCount: count,
          approvalRequiredOperationCount: count,
          createdAt: timestamp,
          updatedAt: timestamp,
        }),
      ),
      workerJobs: z.array(
        z.strictObject({
          type: z.string(),
          status: z.string(),
          count,
          oldestCreatedAt: timestamp.optional(),
        }),
      ),
    }),
    supportAccess: z.strictObject({
      requests: z.array(
        z.strictObject({
          id: identifier,
          status: z.enum(["approved", "pending", "rejected"]),
          requestedByUserId: identifier,
          targetUserId: identifier,
          ttlMinutes: count,
          createdAt: timestamp,
          approvedAt: timestamp.optional(),
          approvedByUserId: identifier.optional(),
          rejectedAt: timestamp.optional(),
          rejectedByUserId: identifier.optional(),
          sessionId: identifier.optional(),
          ticketRef: z.string().optional(),
          reasonHash: z.string().optional(),
          reasonLength: count.optional(),
        }),
      ),
      sessions: z.array(
        z.strictObject({
          sessionId: identifier,
          status: z.enum(["active", "expired", "revoked"]),
          adminUserId: identifier,
          targetUserId: identifier,
          ttlMinutes: count.optional(),
          approvalRequestId: identifier.optional(),
          requestedByUserId: identifier.optional(),
          ticketRef: z.string().optional(),
          reasonHash: z.string().optional(),
          reasonLength: count.optional(),
          expiresAt: timestamp,
          revokedAt: timestamp.optional(),
          createdAt: timestamp,
          createdAuditLogId: identifier,
        }),
      ),
      routeAuditCount: count,
    }),
  })
  .openapi("AccessReviewReport");
export const IdentityLifecyclePolicySchema = z
  .strictObject({
    schema: z.literal("romeo.identity-lifecycle-policy.v1"),
    orgId: identifier,
    generatedAt: timestamp,
    policy: AccessReviewPolicyPostureSchema,
    accountLinking: z.strictObject({
      status: z.literal("disabled"),
      rationale: z.string(),
    }),
    scim: z.strictObject({
      status: z.enum(["disabled", "enabled"]),
      supportedResources: z.array(z.enum(["User", "Group"])),
      rationale: z.string(),
    }),
    groupLifecycle: z.strictObject({
      localAdminSource: z.literal("local"),
      oidcGroupSync: z.literal("additive_known_groups_only"),
      destructiveMembershipSync: z.literal("disabled"),
      unknownExternalGroups: z.literal("ignored"),
    }),
    deprovisioning: z.strictObject({
      localUserDisable: z.literal("revokes_user_api_keys_and_sessions"),
      oidcFeed: z.literal("admin_confirmed_issuer_subject"),
      supportAccess: z.literal("time_bound_approved_audited_revocable"),
    }),
  })
  .openapi("IdentityLifecyclePolicy");
