export const canonicalRunAuditMetadataKeysByAction = {
  "eval.case.create_from_feedback": [
    "agentId",
    "chatId",
    "inputLength",
    "messageId",
    "redaction",
    "sourceRating",
    "suiteId",
  ],
  "eval.result.rate": ["agentId", "hasComment", "rating", "runId"],
  "eval.run": [],
  "eval.run.complete": ["agentId", "score", "status", "suiteId"],
  "eval.suite.create": ["agentId", "caseCount"],
  "image.generate": [
    "artifactCount",
    "estimatedCostUsd",
    "promptLength",
    "providerId",
    "size",
    "unitPriceUsd",
    "workspaceId",
  ],
  "run.cancelled": [
    "agentId",
    "agentVersionId",
    "chatId",
    "modelId",
    "providerId",
    "status",
    "workspaceId",
  ],
  "run.completed": [
    "agentId",
    "agentVersionId",
    "chatId",
    "modelId",
    "providerId",
    "status",
    "workspaceId",
  ],
  "run.failed": [
    "agentId",
    "agentVersionId",
    "chatId",
    "modelId",
    "providerId",
    "status",
    "workspaceId",
  ],
  "run.start": [],
  "tool.connector.auth.check": [
    "available",
    "configured",
    "connectorId",
    "failureCode",
    "secretRefScheme",
  ],
  "tool.connector.auth.update": [
    "authType",
    "configured",
    "oauthScopesCount",
    "oauthTokenUrlConfigured",
    "secretRefScheme",
  ],
  "tool.connector.network_policy.update": [
    "allowPrivateNetwork",
    "allowedHostCount",
    "mode",
  ],
  "tool.connector.update": ["enabled"],
  "tool.dispatch": [],
  "tool.execute": [
    "agentId",
    "approvalPolicy",
    "approvalRequestId",
    "approvalRequired",
    "bindingId",
    "bound",
    "connectorId",
    "enabled",
    "errorCode",
    "inputKeys",
    "jobId",
    "method",
    "operationId",
    "path",
    "payloadStorage",
    "riskLevel",
    "workerQueue",
  ],
  "tool.operation.dispatch": [
    "approvalPolicy",
    "approvalRequestId",
    "authInjected",
    "bodyKeys",
    "connectorId",
    "errorCode",
    "host",
    "jobId",
    "method",
    "operationId",
    "parameterKeys",
    "path",
    "responseBodyBytes",
    "responseOk",
    "responseSchemaValidation",
    "responseStatus",
    "responseTruncated",
    "riskLevel",
  ],
  "tool.operation.dispatch.enqueue": [
    "approvalPolicy",
    "approvalRequestId",
    "bodyKeys",
    "connectorId",
    "errorCode",
    "host",
    "idempotencyKeyHash",
    "idempotencyReplay",
    "jobId",
    "method",
    "operationId",
    "parameterKeys",
    "path",
    "payloadStorage",
    "riskLevel",
    "workerQueue",
  ],
  "tool.operation.dispatch_request.cancel": [
    "bodyKeys",
    "connectorId",
    "errorCode",
    "host",
    "jobId",
    "method",
    "operationId",
    "parameterKeys",
    "path",
    "payloadStorage",
    "reasonCode",
    "runId",
    "workerQueue",
  ],
  "tool.operation.dispatch_request.complete": [
    "bodyKeys",
    "connectorId",
    "host",
    "jobId",
    "method",
    "operationId",
    "parameterKeys",
    "path",
    "payloadStorage",
    "responseBodyBytes",
    "responseOk",
    "responseSchemaValidation",
    "responseStatus",
    "responseTruncated",
    "workerQueue",
  ],
  "tool.operation.dispatch_request.dead_letter": [
    "attempts",
    "bodyKeys",
    "connectorId",
    "errorCode",
    "host",
    "jobId",
    "maxAttempts",
    "method",
    "nextAttempt",
    "operationId",
    "parameterKeys",
    "path",
    "payloadStorage",
    "reasonCode",
    "workerQueue",
  ],
  "tool.operation.dispatch_request.expire": [
    "ageSeconds",
    "bodyKeys",
    "connectorId",
    "errorCode",
    "expiredAt",
    "expiredBy",
    "host",
    "jobId",
    "leaseExpiredSeconds",
    "method",
    "operationId",
    "parameterKeys",
    "path",
    "payloadStorage",
    "queuedTimeoutSeconds",
    "reasonCode",
    "runningTimeoutSeconds",
    "workerId",
    "workerQueue",
  ],
  "tool.operation.dispatch_request.fail": [
    "bodyKeys",
    "connectorId",
    "errorCode",
    "host",
    "jobId",
    "method",
    "operationId",
    "parameterKeys",
    "path",
    "payloadStorage",
    "workerQueue",
  ],
  "tool.operation.dispatch_request.payload.read": [
    "bodyKeys",
    "connectorId",
    "host",
    "jobId",
    "method",
    "operationId",
    "parameterKeys",
    "path",
    "payloadStorage",
    "payloadStoreDriver",
    "workerQueue",
  ],
  "tool.operation.approval.approve": [
    "agentId",
    "approvalRequestId",
    "bodyKeyCount",
    "connectorId",
    "decision",
    "method",
    "operationId",
    "parameterKeyCount",
    "path",
    "runId",
    "workspaceId",
  ],
  "tool.operation.approval.cancel": [
    "agentId",
    "approvalRequestId",
    "bodyKeyCount",
    "connectorId",
    "decision",
    "errorCode",
    "method",
    "operationId",
    "parameterKeyCount",
    "path",
    "runId",
    "workspaceId",
  ],
  "tool.operation.approval.reject": [
    "agentId",
    "approvalRequestId",
    "bodyKeyCount",
    "connectorId",
    "decision",
    "errorCode",
    "method",
    "operationId",
    "parameterKeyCount",
    "path",
    "runId",
    "workspaceId",
  ],
  "tool.operation.test": [
    "bodyKeys",
    "connectorId",
    "disabledReasons",
    "method",
    "operationId",
    "parameterKeys",
    "path",
  ],
  "tool.operation.update": ["connectorId", "enabled", "operationId"],
  "tool.approval.approve": [
    "agentId",
    "approvalRequestId",
    "decision",
    "inputKeyCount",
    "workspaceId",
  ],
  "tool.approval.cancel": [
    "agentId",
    "approvalRequestId",
    "decision",
    "errorCode",
    "inputKeyCount",
    "workspaceId",
  ],
  "tool.approval.reject": [
    "agentId",
    "approvalRequestId",
    "decision",
    "errorCode",
    "inputKeyCount",
    "runId",
    "workspaceId",
  ],
  "voice.artifact.delete": [
    "artifactId",
    "objectDeleted",
    "rawStorageKeyReturned",
    "storageKeyHash",
  ],
  "voice.catalog_sync": [
    "existingCount",
    "importedCount",
    "providerIds",
    "providerVoiceCount",
  ],
  "voice.message.generated": [],
  "voice.preview.generated": [],
  "voice.profile.create": [
    "providerId",
    "providerVoiceConfigured",
    "styleTagCount",
  ],
  "voice.request": [],
  "voice.synthesis": [],
  "voice.transcription": [],
  "voice.transcription.generated": [],
  "web_search.query": [
    "freshnessExcludedCount",
    "provider",
    "queryHash",
    "resultCount",
  ],
  "web_url.ingest": [
    "hosts",
    "requestedUrlCount",
    "unreachableCount",
    "unreachablePolicy",
    "urlCount",
  ],
  "worker.claim": ["attempt", "leaseSeconds"],
  "worker.complete": ["artifactCount", "finalHost", "navigationCount"],
  "worker.dead_letter": [
    "errorCode",
    "maxAttempts",
    "nextAttempt",
    "reasonCode",
  ],
  "worker.enqueue": [],
  "worker.expire": ["errorCode", "reasonCode"],
  "worker.fail": ["errorCode"],
  "worker.renew_lease": ["leaseSeconds"],
  "workflow.browser_task.approve": [
    "jobId",
    "status",
    "stepId",
    "targetHost",
    "targetOrigin",
    "workerQueue",
    "workflowId",
  ],
  "workflow.browser_task.artifact.register": [
    "artifactCount",
    "artifactId",
    "artifactType",
    "contentType",
    "jobId",
    "sizeBytes",
    "stepId",
    "targetHost",
    "targetOrigin",
    "workerQueue",
    "workflowId",
    "workflowRunId",
  ],
  "workflow.browser_task.complete": [
    "artifactCount",
    "currentStepId",
    "finalHost",
    "navigationCount",
    "status",
    "stepId",
    "workerQueue",
    "workflowId",
  ],
  "workflow.browser_task.fail": [
    "currentStepId",
    "errorCode",
    "status",
    "stepId",
    "workerQueue",
    "workflowId",
  ],
  "workflow.browser_task.worker.claim": [
    "attempt",
    "jobId",
    "leaseSeconds",
    "stepId",
    "targetHost",
    "targetOrigin",
    "workerQueue",
    "workflowId",
  ],
  "workflow.browser_task.worker.complete": [
    "artifactCount",
    "finalHost",
    "jobId",
    "navigationCount",
    "stepId",
    "targetHost",
    "targetOrigin",
    "workerQueue",
    "workflowId",
  ],
  "workflow.browser_task.worker.dead_letter": [],
  "workflow.browser_task.worker.expire": [],
  "workflow.browser_task.worker.fail": [],
  "workflow.browser_task.worker.renew_lease": [],
  "workflow.create": ["stepCount", "workspaceId"],
  "workflow.run": [],
  "workflow.run.approve": ["currentStepId", "status", "workflowId"],
  "workflow.run.recover": [
    "currentStepId",
    "linkedRunId",
    "linkedRunStatus",
    "recoveryAction",
    "status",
    "workflowId",
  ],
  "workflow.run.resume": [
    "currentStepId",
    "linkedRunId",
    "linkedRunIds",
    "linkedRunStatus",
    "linkedRunStatuses",
    "status",
    "workflowId",
  ],
  "workflow.run.retry": [
    "attempt",
    "currentStepId",
    "linkedRunId",
    "linkedRunStatus",
    "retryRunId",
    "status",
    "workflowId",
  ],
  "workflow.run.start": ["currentStepId", "status", "workflowId"],
  "workflow.template.create": ["templateId", "workspaceId"],
} as const;
