export const canonicalDataAuditMetadataKeysByAction = {
  "artifact.register": [
    "artifactCount",
    "artifactId",
    "artifactType",
    "contentType",
    "sizeBytes",
    "workflowRunId",
  ],
  "connector.sync": [],
  "data_connector.create": ["knowledgeBaseId", "type"],
  "data_connector.sync": [
    "createdSourceCount",
    "deletedSourceCount",
    "errorCode",
    "reusedSourceCount",
    "sourceCount",
    "syncId",
  ],
  "file.create": ["mimeType", "purpose", "sizeBytes", "workspaceId"],
  "file.delete": ["mimeType", "purpose", "sizeBytes", "workspaceId"],
  "file.extraction.retry": [
    "attempts",
    "extractionStatus",
    "failureCode",
    "method",
    "workspaceId",
  ],
  "file.lifecycle.retry": ["attempts", "failureCode", "workspaceId"],
  "file.reference.attach": ["messageId", "referenceCount", "workspaceId"],
  "model.capability.probe": ["featureCount", "providerId"],
  "model.capability.override": ["source"],
  "file.resumable_upload.complete": [
    "mimeType",
    "partCount",
    "partSizeBytes",
    "purpose",
    "sizeBytes",
    "workspaceId",
  ],
  "file.resumable_upload.create": [
    "mimeType",
    "partCount",
    "partSizeBytes",
    "purpose",
    "sizeBytes",
    "workspaceId",
  ],
  "file.upload": [],
  "file.upload_session.complete": [
    "mimeType",
    "purpose",
    "sizeBytes",
    "workspaceId",
  ],
  "file.upload_session.create": [
    "mimeType",
    "purpose",
    "sizeBytes",
    "workspaceId",
  ],
  "folder.create": ["workspaceId"],
  "folder.delete": [
    "childFoldersReparented",
    "folderItemsRemoved",
    "workspaceId",
  ],
  "folder.item.add": ["resourceId", "resourceType"],
  "folder.item.delete": ["resourceId", "resourceType"],
  "folder.update": [
    "changedData",
    "changedExpanded",
    "changedMeta",
    "changedName",
    "changedParent",
    "workspaceId",
  ],
  "knowledge.embedding.index": [
    "dimensions",
    "embeddingCount",
    "jobId",
    "model",
    "providerId",
  ],
  "knowledge.ingest": [],
  "knowledge.query.tiered": [
    "actorSubjectType",
    "authorizedCount",
    "externalVectorStoreConfigured",
    "externalVectorStoreDriver",
    "externalVectorStoreRoutingActive",
    "isolationMode",
    "knowledgeBaseIds",
    "latencyMs",
    "namespaceConfigured",
    "namespacePolicy",
    "partitioningConfigured",
    "partitioningPolicy",
    "ragPolicyEnabledTiers",
    "ragPolicySource",
    "requestedCount",
    "resultCountsByTier",
    "retrievalFallbackReasons",
    "retrievalRouteModes",
    "skipped",
    "tierCounts",
    "vectorDriver",
    "vectorEmbeddingModels",
    "vectorProviderIds",
    "serviceAccountId",
  ],
  "knowledge.replay.compare": [
    "baseline",
    "candidate",
    "deltas",
    "outcome",
    "serviceAccountId",
  ],
  "knowledge.replay.tiered": [
    "averageLatencyMs",
    "averagePrecision",
    "averageRecall",
    "caseCount",
    "expectedChunkCount",
    "hitCount",
    "matchedExpectedChunkCount",
    "status",
  ],
  "knowledge.source.delete": [
    "actorSubjectType",
    "chunkCount",
    "deleteVectorsOnSourceDelete",
    "embeddingCount",
    "exportIncludesEmbeddingVectors",
    "knowledgeBaseId",
    "objectDeleted",
    "ragPolicySource",
    "serviceAccountId",
    "sourceId",
    "workspaceId",
  ],
  "knowledge_base.create": [
    "actorSubjectType",
    "descriptionConfigured",
    "scope",
    "serviceAccountId",
    "workspaceId",
  ],
  "knowledge_base.update": [
    "actorSubjectType",
    "changedFields",
    "descriptionConfigured",
    "workspaceId",
  ],
} as const;
