export const auditMetadataKeysByAction = {
  "idempotency.receipt.claim": [],
  "abuse_control.enforcement_blocked": [],
  "admin.abuse_controls.update": [],
  "admin.auth_provider_settings.update": [],
  "admin.capability_assignment.replace": [],
  "admin.capability_flag.replace": [],
  "admin.policy_bundle.approve": [],
  "admin.policy_bundle.propose": [],
  "admin.table_export.create": [],
  "admin.table_view.replace": [],
  "admin.content_policy.simulate": [],
  "admin.content_policy.update": [],
  "admin.content_policy.version.create": [],
  "admin.content_policy.version.publish": [],
  "admin.content_policy.rollback": [],
  "admin.content_policy.approval.request": [],
  "admin.content_policy.approval.resolve": [],
  "content_policy.enforce": [],
  "admin.managed_secret.create": [],
  "admin.notification_policy.update": [],
  "admin.organization.create": [],
  "admin.organization.deletion_finalization_evidence": [],
  "admin.organization.deletion_request": [],
  "admin.organization.deletion_request.cancel": [],
  "admin.organization.reactivate": [],
  "admin.organization.suspend": [],
  "admin.organization.update": [],
  "admin.rag_policy.change_request.approve": [],
  "admin.rag_policy.change_request.create": [],
  "admin.rag_policy.change_request.reject": [],
  "admin.rag_policy.update": [],
  "admin.secret_rotation.rewrap": [],
  "admin.sso_oidc.deprovision": [],
  "admin.sso_settings.update": ["resourceId", "resourceType"],
  "agent.archive": ["workspaceId"],
  "agent.clone": [
    "baseModelId",
    "knowledgeBindingsCopied",
    "sourceAgentId",
    "workspaceId",
  ],
  "agent.create": [
    "baseModelId",
    "memoryMode",
    "parameterKeys",
    "safetyConfigured",
    "workspaceId",
  ],
  "agent.customization_policy.update": [],
  "agent.export": ["baseModelId", "bindingCounts", "workspaceId"],
  "agent.import": [
    "baseModelId",
    "bindingCounts",
    "parameterKeys",
    "workspaceId",
  ],
  "agent.knowledge_binding.update": [],
  "agent.preferences.clear": [],
  "agent.preferences.update": [],
  "agent.share": ["permissions", "principalType"],
  "agent.share.revoke": [],
  "agent.tool_binding.update": [],
  "agent.update": [
    "changedFields",
    "memoryMode",
    "parameterKeys",
    "safetyConfigured",
    "workspaceId",
  ],
  "agent.version.publish": [
    "agentId",
    "baseModelId",
    "channel",
    "version",
    "workspaceId",
  ],
  "agent.version.rollback": ["baseModelId", "versionId", "workspaceId"],
  "api_key.create": [],
  "api_key.revoke": [],
  "artifact.register": [
    "artifactCount",
    "artifactId",
    "artifactType",
    "contentType",
    "sizeBytes",
    "workflowRunId",
  ],
  "auth.ldap.login.failure": [],
  "auth.ldap.login.success": [],
  "auth.oauth2.login.success": [],
  "auth.saml.login.failure": [],
  "auth.saml.login.success": [],
  "billing.entitlements_reconciled": [],
  "billing.external_event_ignored": [],
  "billing.external_event_synced": [],
  "billing.lifecycle_enforced": [],
  "billing.plan_applied": [],
  "channel.create": ["memberCount", "private", "type", "workspaceId"],
  "channel.delete": ["type"],
  "channel.members.add": ["addedMemberCount"],
  "channel.members.remove": ["removedMemberCount"],
  "channel.message.create": [
    "messageId",
    "parentMessagePresent",
    "replyToMessagePresent",
  ],
  "channel.message.delete": ["deleted", "messageId"],
  "channel.message.pin": ["messageId", "pinned"],
  "channel.message.reaction.add": ["messageId", "reactionNameHash"],
  "channel.message.reaction.remove": ["messageId", "reactionNameHash"],
  "channel.message.update": ["messageId"],
  "channel.read": [],
  "channel.update": [
    "addedMemberCount",
    "changedDescription",
    "changedName",
    "changedPrivacy",
    "type",
  ],
  "chat.archive": ["archivedAt"],
  "chat.attachment.retention.update": [],
  "chat.comment": [],
  "chat.delete": [],
  "chat.export": ["messageCount"],
  "chat.fork": [
    "copiedAttachmentCount",
    "copiedMessageCount",
    "includedAttachments",
    "sourceChatId",
    "throughMessageIdConfigured",
  ],
  "chat.import": ["messageCount"],
  "chat.legal_hold.clear": ["clearedAt"],
  "chat.legal_hold.update": ["hasReason", "legalHoldUntil"],
  "chat.message.delete": [],
  "chat.message_feedback.clear": [],
  "chat.message_feedback.record": [],
  "chat.share": ["permissions", "principalType"],
  "chat.share.revoke": ["permission", "principalType"],
  "chat.tag.assign": [],
  "chat.tag.remove": [],
  "chat.temporary.cleanup": [],
  "chat.temporary.cleanup.worker": [],
  "chat.temporary.expired": [],
  "chat.unarchive": ["unarchivedAt"],
  "chat.update": ["changedFields"],
  "chat_experience.update": [],
  "memory.create": [],
  "memory.delete": [],
  "memory.update": [],
  "note.create": [],
  "note.delete": [],
  "note.update": [],
  "connector.sync": [],
  "data_connector.create": ["knowledgeBaseId", "type"],
  "data_connector.sync": [
    "createdSourceCount",
    "deletedSourceCount",
    "errorCode",
    "reusedSourceCount",
    "sourceCount",
    "syncId",
  ],
  "device_authorization.create": ["scopeCount"],
  "device_authorization.refresh": ["scopeCount"],
  "device_authorization.revoke": [],
  "delegated_oauth.connect": [],
  "delegated_oauth.refresh": [],
  "delegated_oauth.revoke": [],
  "directory_sync.apply": ["reason"],
  "directory_sync.preview": ["reason"],
  "eval.case.create_from_feedback": [],
  "eval.result.rate": ["agentId", "hasComment", "rating", "runId"],
  "eval.run": [],
  "eval.run.complete": ["agentId", "score", "status", "suiteId"],
  "eval.suite.create": ["agentId", "caseCount"],
  "file.create": ["mimeType", "purpose", "sizeBytes"],
  "file.delete": ["mimeType", "purpose", "sizeBytes"],
  "file.extraction.retry": [
    "attempts",
    "extractionStatus",
    "failureCode",
    "method",
  ],
  "file.lifecycle.retry": ["attempts", "failureCode"],
  "file.reference.attach": ["messageId", "referenceCount"],
  "model.capability.probe": [],
  "model.capability.override": [],
  "file.resumable_upload.complete": [
    "mimeType",
    "partCount",
    "partSizeBytes",
    "purpose",
    "sizeBytes",
  ],
  "file.resumable_upload.create": [
    "mimeType",
    "partCount",
    "partSizeBytes",
    "purpose",
    "sizeBytes",
  ],
  "file.share": ["permissions", "principalType"],
  "file.upload": [],
  "file.upload_session.complete": ["mimeType", "purpose", "sizeBytes"],
  "file.upload_session.create": ["mimeType", "purpose", "sizeBytes"],
  "folder.create": ["workspaceId"],
  "folder.delete": [
    "childFoldersReparented",
    "folderItemsRemoved",
    "workspaceId",
  ],
  "folder.item.add": ["resourceId", "resourceType"],
  "folder.item.delete": ["resourceId", "resourceType"],
  "folder.share": ["permissions", "principalType"],
  "folder.update": [
    "changedData",
    "changedExpanded",
    "changedMeta",
    "changedName",
    "changedParent",
    "workspaceId",
  ],
  "governance.data_deletion.execute": [],
  "governance.data_export.execute": [],
  "governance.data_export.package.create": [],
  "governance.data_export.package.delete": [],
  "governance.retention.enforce": [],
  "governance.retention.update": [],
  "group.create": ["slug"],
  "group.member.add": ["userId"],
  "group.member.remove": ["userId"],
  "image.generate": [],
  "knowledge.embedding.index": [],
  "knowledge.ingest": [],
  "knowledge.query.tiered": [],
  "knowledge.replay.compare": [],
  "knowledge.replay.tiered": [],
  "knowledge.source.delete": [],
  "knowledge_base.create": ["scope"],
  "knowledge_base.share": ["permissions", "principalType"],
  "knowledge_base.share.revoke": [],
  "knowledge_base.update": ["changedFields"],
  "local_auth.login": [],
  "local_auth.login.failure": [],
  "local_auth.login.mfa_required": [],
  "local_auth.mfa.confirm": [],
  "local_auth.mfa.disable": [],
  "local_auth.mfa.enroll": [],
  "local_auth.mfa.recovery_code.consume": [],
  "local_auth.mfa.recovery_codes.generate": [],
  "local_auth.password.admin_set": [],
  "local_auth.password.set": [],
  "model.capabilities.update": [],
  "model.enabled.update": [],
  "model.pricing.update": ["priceFields", "providerId"],
  "model.request": [],
  "model.share": ["permissions", "principalType", "providerId"],
  "model.share.revoke": ["permission", "principalId", "principalType"],
  "prompt_template.create": ["tagCount", "visibility", "workspaceId"],
  "prompt_template.delete": ["visibility", "workspaceId"],
  "prompt_template.share": ["permissions", "principalType"],
  "prompt_template.update": ["changedFields", "tagCount", "visibility"],
  "provider.create": ["credentialConfigured", "enabled", "providerType"],
  "provider.model.delete": ["model", "status"],
  "provider.model.pull": ["model", "status"],
  "provider.models.sync": [],
  "provider.update": ["credentialConfigured", "enabled", "modelIdCount"],
  "quota.create": ["limit", "resetInterval"],
  "quota.delete": ["limit", "resetInterval"],
  "quota.update": [
    "changedLimit",
    "changedResetInterval",
    "limit",
    "resetInterval",
    "resetUsage",
  ],
  "resource.favorite": [],
  "run.cancelled": [],
  "run.completed": [],
  "run.failed": [],
  "run.start": [],
  "scim.group.create": ["memberCount"],
  "scim.group.delete": [],
  "scim.group.patch": [],
  "scim.group.replace": ["displayNameChanged", "memberCount"],
  "scim.user.create": ["active", "suppliedActive"],
  "scim.user.deactivate": ["credentialRevocation", "destructiveDelete"],
  "scim.user.patch": [],
  "scim.user.replace": [
    "active",
    "activeChanged",
    "emailChanged",
    "nameChanged",
  ],
  "service_account.create": [],
  "service_account.disable": [],
  "session.create": [],
  "session.revoke": [],
  "support.impersonation.create": [],
  "support.impersonation.request": [],
  "support.impersonation.request.approve": [],
  "support.impersonation.request.create": ["resourceType"],
  "support.impersonation.request.reject": ["resourceType"],
  "support.impersonation.revoke": [],
  "tool.connector.auth.check": [],
  "tool.connector.auth.update": [],
  "tool.connector.network_policy.update": [],
  "tool.connector.update": [],
  "tool.dispatch": [],
  "tool.execute": [],
  "tool.operation.dispatch": [],
  "tool.operation.dispatch.enqueue": [],
  "tool.operation.dispatch_request.cancel": [],
  "tool.operation.dispatch_request.complete": [],
  "tool.operation.dispatch_request.dead_letter": [],
  "tool.operation.dispatch_request.expire": [],
  "tool.operation.dispatch_request.fail": [],
  "tool.operation.dispatch_request.payload.read": [],
  "tool.operation.approval.approve": [],
  "tool.operation.approval.cancel": [],
  "tool.operation.approval.reject": [],
  "tool.operation.test": [],
  "tool.operation.update": [],
  "tool.approval.approve": [],
  "tool.approval.cancel": [],
  "tool.approval.reject": [],
  "user.disable": [],
  "user.profile.update": [],
  "user.role.update": [],
  "voice.artifact.delete": [],
  "voice.catalog_sync": [],
  "voice.message.generated": [],
  "voice.preview.generated": [],
  "voice.profile.create": [],
  "voice.request": [],
  "voice.synthesis": [],
  "voice.transcription": [],
  "voice.transcription.generated": [],
  "web_search.configuration.update": [],
  "web_search.query": [],
  "web_url.ingest": [],
  "webhook.bulk_disable": [],
  "webhook.create": [],
  "webhook.delivery": [],
  "webhook.disable": [],
  "webhook.test": [],
  "worker.claim": ["attempt", "leaseSeconds"],
  "worker.complete": ["artifactCount", "finalHost", "navigationCount"],
  "worker.dead_letter": [
    "errorCode",
    "maxAttempts",
    "nextAttempt",
    "reasonCode",
  ],
  "worker.enqueue": [],
  "worker.expire": ["errorCode", "reasonCode"],
  "worker.fail": ["errorCode"],
  "worker.renew_lease": ["leaseSeconds"],
  "workflow.browser_task.approve": [
    "jobId",
    "status",
    "stepId",
    "targetHost",
    "targetOrigin",
    "workerQueue",
    "workflowId",
  ],
  "workflow.browser_task.artifact.register": [],
  "workflow.browser_task.complete": [
    "artifactCount",
    "currentStepId",
    "finalHost",
    "navigationCount",
    "status",
    "stepId",
    "workerQueue",
    "workflowId",
  ],
  "workflow.browser_task.fail": [
    "currentStepId",
    "errorCode",
    "status",
    "stepId",
    "workerQueue",
    "workflowId",
  ],
  "workflow.browser_task.worker.claim": [],
  "workflow.browser_task.worker.complete": [],
  "workflow.browser_task.worker.dead_letter": [],
  "workflow.browser_task.worker.expire": [],
  "workflow.browser_task.worker.fail": [],
  "workflow.browser_task.worker.renew_lease": [],
  "workflow.create": ["stepCount", "workspaceId"],
  "workflow.run": [],
  "workflow.run.approve": ["currentStepId", "status", "workflowId"],
  "workflow.run.recover": [],
  "workflow.run.resume": [],
  "workflow.run.retry": [],
  "workflow.run.start": ["currentStepId", "status", "workflowId"],
  "workflow.template.create": ["templateId", "workspaceId"],
  "workspace.archive": ["archivedAt"],
  "workspace.create": ["slug"],
  "workspace.default_agent.update": ["agentId"],
  "workspace.export": ["counts"],
  "workspace.member.add": ["principalId", "principalType"],
  "workspace.member.remove": ["principalId", "principalType"],
} as const;
