export const canonicalSecurityAuditMetadataKeysByAction = {
  "auth.ldap.login.failure": [
    "failureClass",
    "identifierHash",
    "locked",
    "providerId",
  ],
  "auth.ldap.login.success": [
    "adminGroupPolicyActive",
    "allowedDomainPolicyActive",
    "groupCount",
    "mappedGroupCount",
    "providerId",
    "requiredGroupCount",
  ],
  "auth.oauth2.login.success": [
    "adminTeamMatched",
    "allowedDomainPolicyActive",
    "externalGroupCount",
    "providerAccountHash",
    "providerId",
    "requiredOrganizationCount",
    "requiredTeamCount",
  ],
  "auth.saml.login.failure": ["failureClass", "providerId", "requestIdHash"],
  "auth.saml.login.success": [
    "adminGroupPolicyActive",
    "allowedDomainPolicyActive",
    "groupCount",
    "mappedGroupCount",
    "providerId",
    "requiredGroupCount",
    "signedAssertionRequired",
    "signedResponseRequired",
    "subjectHash",
  ],
  "directory_sync.apply": [
    "disableMissingUsers",
    "groupRemovalCount",
    "membershipRemovalCount",
    "mode",
    "preserveAdminUsers",
    "reason",
    "reasonProvided",
    "redaction",
    "removeMissingGroupMembers",
    "schema",
    "skippedAdminUserCount",
    "skippedSelfUserCount",
    "source",
    "status",
    "userDisableCount",
    "warningCodes",
  ],
  "directory_sync.preview": [
    "disableMissingUsers",
    "groupRemovalCount",
    "membershipRemovalCount",
    "mode",
    "preserveAdminUsers",
    "reason",
    "reasonProvided",
    "redaction",
    "removeMissingGroupMembers",
    "schema",
    "skippedAdminUserCount",
    "skippedSelfUserCount",
    "source",
    "status",
    "userDisableCount",
    "warningCodes",
  ],
  "local_auth.login": ["challenge", "mfaSatisfied", "passwordCredentialId"],
  "local_auth.login.failure": [
    "factorType",
    "failureClass",
    "identifierHash",
    "identifierHashAlgorithm",
    "locked",
    "providerId",
  ],
  "local_auth.login.mfa_required": ["factorCount", "methods"],
  "local_auth.mfa.confirm": ["type"],
  "local_auth.mfa.disable": ["type"],
  "local_auth.mfa.enroll": ["type"],
  "local_auth.mfa.recovery_code.consume": ["remainingCount", "type"],
  "local_auth.mfa.recovery_codes.generate": ["codeCount", "type"],
  "local_auth.password.admin_set": [],
  "local_auth.password.set": ["selfService", "sessionsRevoked"],
  "scim.group.create": ["memberCount", "schema"],
  "scim.group.delete": [
    "destructiveDelete",
    "membershipCount",
    "revokedGrantCount",
    "schema",
  ],
  "scim.group.patch": [
    "displayNameChanged",
    "membersAdded",
    "membersRemoved",
    "schema",
  ],
  "scim.group.replace": ["displayNameChanged", "memberCount"],
  "scim.user.create": ["active", "schema", "suppliedActive"],
  "scim.user.deactivate": ["credentialRevocation", "destructiveDelete"],
  "scim.user.patch": ["activeChanged", "emailChanged", "nameChanged", "schema"],
  "scim.user.replace": [
    "active",
    "activeChanged",
    "emailChanged",
    "nameChanged",
  ],
  "support.impersonation.create": [
    "approvalRequestId",
    "reasonHash",
    "reasonLength",
    "requestedByUserId",
    "scopeCount",
    "targetUserId",
    "ticketRef",
    "ttlMinutes",
  ],
  "support.impersonation.request": [
    "accessType",
    "accessedResourceId",
    "accessedResourceType",
    "adminUserId",
    "method",
    "path",
    "queryKeys",
    "status",
    "supportSessionCreatedAuditLogId",
  ],
  "support.impersonation.request.approve": [
    "approvalRequestId",
    "requestedByUserId",
    "sessionId",
    "targetUserId",
    "ticketRef",
    "ttlMinutes",
  ],
  "support.impersonation.request.create": [
    "reasonHash",
    "reasonLength",
    "resourceType",
    "scopeCount",
    "targetUserId",
    "ticketRef",
    "ttlMinutes",
  ],
  "support.impersonation.request.reject": [
    "approvalRequestId",
    "requestedByUserId",
    "resourceType",
    "targetUserId",
    "ttlMinutes",
  ],
  "support.impersonation.revoke": [
    "adminUserId",
    "createdAuditLogId",
    "previousStatus",
    "targetUserId",
    "ticketRef",
  ],
} as const;
