export const canonicalChatAuditMetadataKeysByAction = {
  "channel.create": ["memberCount", "private", "type", "workspaceId"],
  "channel.delete": ["type"],
  "channel.members.add": ["addedMemberCount"],
  "channel.members.remove": ["removedMemberCount"],
  "channel.message.create": [
    "messageId",
    "parentMessagePresent",
    "replyToMessagePresent",
  ],
  "channel.message.delete": ["deleted", "messageId"],
  "channel.message.pin": ["messageId", "pinned"],
  "channel.message.reaction.add": ["messageId", "reactionNameHash"],
  "channel.message.reaction.remove": ["messageId", "reactionNameHash"],
  "channel.message.update": ["messageId"],
  "channel.read": [],
  "channel.update": [
    "addedMemberCount",
    "changedDescription",
    "changedName",
    "changedPrivacy",
    "type",
  ],
  "chat.archive": ["archivedAt", "workspaceId"],
  "chat.attachment.retention.update": [
    "attachmentId",
    "retainedInContext",
    "workspaceId",
  ],
  "chat.comment": ["mentionedUserIds"],
  "chat.delete": [
    "confirmationMatched",
    "counts",
    "deletionEngine",
    "workspaceId",
  ],
  "chat.export": ["messageCount", "workspaceId"],
  "chat.fork": [
    "copiedAttachmentCount",
    "copiedMessageCount",
    "includedAttachments",
    "sourceChatId",
    "throughMessageIdConfigured",
    "workspaceId",
  ],
  "chat.import": ["messageCount", "workspaceId"],
  "chat.legal_hold.clear": ["clearedAt", "workspaceId"],
  "chat.legal_hold.update": ["hasReason", "legalHoldUntil", "workspaceId"],
  "chat.message.delete": ["messageId", "messageRole", "workspaceId"],
  "chat.message_feedback.clear": [
    "configured",
    "messageId",
    "messageRole",
    "rating",
    "reasonCodeConfigured",
    "workspaceId",
  ],
  "chat.message_feedback.record": [
    "configured",
    "messageId",
    "messageRole",
    "rating",
    "reasonCodeConfigured",
    "workspaceId",
  ],
  "chat.tag.assign": ["tagId", "tagNameReturned", "tagSlugHash", "workspaceId"],
  "chat.tag.remove": [
    "orphanDeleted",
    "tagId",
    "tagNameReturned",
    "tagSlugHash",
    "workspaceId",
  ],
  "chat.temporary.cleanup": [
    "deletedCount",
    "skippedLegalHoldCount",
    "workspaceId",
  ],
  "chat.temporary.cleanup.worker": [
    "deleted",
    "deletedObjects",
    "scanned",
    "skippedLegalHold",
  ],
  "chat.temporary.expired": ["workspaceId"],
  "chat.unarchive": ["unarchivedAt", "workspaceId"],
  "chat.update": ["changedFields", "workspaceId"],
  "chat_experience.update": [
    "assistantsEnabled",
    "autoTitleEnabled",
    "suggestionCount",
  ],
  "memory.create": ["contentKind", "contentScope", "workspaceId"],
  "memory.delete": ["contentKind", "contentScope", "workspaceId"],
  "memory.update": ["contentKind", "contentScope", "workspaceId"],
  "note.create": ["contentKind", "contentScope", "workspaceId"],
  "note.delete": ["contentKind", "contentScope", "workspaceId"],
  "note.update": ["contentKind", "contentScope", "workspaceId"],
} as const;
