export const canonicalAccessAuditMetadataKeysByAction = {
  "agent.share": ["permissions", "principalType"],
  "agent.share.revoke": ["permission", "principalId", "principalType"],
  "api_key.create": [],
  "api_key.revoke": [],
  "chat.share": ["permissions", "principalType"],
  "chat.share.revoke": ["permission", "principalType"],
  "file.share": ["permissions", "principalType"],
  "folder.share": ["permissions", "principalType"],
  "group.create": ["slug"],
  "group.member.add": ["userId"],
  "group.member.remove": ["userId"],
  "knowledge_base.share": ["permissions", "principalType"],
  "knowledge_base.share.revoke": ["permission", "principalId", "principalType"],
  "model.share": ["permissions", "principalType", "providerId"],
  "model.share.revoke": ["permission", "principalId", "principalType"],
  "prompt_template.share": ["permissions", "principalType"],
  "resource.favorite": [],
  "service_account.create": [],
  "service_account.disable": [],
  "workspace.member.add": ["principalId", "principalType"],
  "workspace.member.remove": ["principalId", "principalType"],
} as const;
