export const canonicalAdminAuditMetadataKeysByAction = {
  "abuse_control.enforcement_blocked": [
    "action",
    "agentId",
    "connectorId",
    "providerId",
    "reasonCodes",
    "toolId",
    "workerClass",
    "workspaceId",
  ],
  "admin.abuse_controls.update": [
    "allowedBillingStatuses",
    "costWorkBlocked",
    "defaultBlockReasons",
    "denyWhenBillingPlanMissing",
    "enforceBillingStatus",
    "killSwitchCounts",
    "reasonCodeChanged",
    "suspended",
    "suspensionChanged",
  ],
  "admin.auth_provider_settings.update": [
    "changeSummary",
    "changedScopes",
    "enabledProviderIds",
    "globalProviderCount",
    "ldapConfiguredProviderIds",
    "localFallbackEnabled",
    "oauth2ConfiguredProviderIds",
    "oidcConfiguredProviderIds",
    "orgId",
    "orgOverrideProviderCount",
    "samlConfiguredProviderIds",
    "secretRefConfiguredCount",
  ],
  "admin.capability_assignment.replace": [
    "capabilityId",
    "configurationFields",
    "expires",
    "scopeId",
    "scopeType",
    "state",
    "version",
  ],
  "admin.capability_flag.replace": [
    "allowlistedSubjectCount",
    "flagId",
    "state",
    "version",
  ],
  "admin.policy_bundle.approve": [
    "capabilityId",
    "publicationRequired",
    "reasonLength",
  ],
  "admin.policy_bundle.propose": [
    "capabilityId",
    "classCount",
    "publicationRequired",
  ],
  "admin.table_export.create": ["estimatedRows", "mode", "resource"],
  "admin.table_view.replace": ["resource", "source"],
  "admin.content_policy.simulate": ["detectors"],
  "admin.content_policy.update": ["detectors"],
  "admin.content_policy.version.create": ["state", "version"],
  "admin.content_policy.version.publish": ["state", "version"],
  "admin.content_policy.rollback": ["state", "version"],
  "admin.content_policy.approval.request": ["runId", "state"],
  "admin.content_policy.approval.resolve": ["runId", "state"],
  "content_policy.enforce": ["detectors"],
  "admin.managed_secret.create": [
    "nameConfigured",
    "orgId",
    "purpose",
    "scope",
    "secretRefScheme",
    "storageDriver",
    "targetRefProvided",
  ],
  "admin.notification_policy.update": [
    "allowedChannelTypeCount",
    "allowedEmailDomainCount",
    "allowedSlackHostCount",
    "allowedTeamsHostCount",
    "allowedWebhookHostCount",
    "deliveryEnabledChanged",
    "posture",
    "suppressedNotificationTypeCount",
  ],
  "admin.organization.create": [
    "defaultWorkspaceCreated",
    "initialAdminCreated",
    "localPasswordConfigured",
  ],
  "admin.organization.deletion_finalization_evidence": [
    "controlCount",
    "controls",
    "rawEvidenceReturned",
  ],
  "admin.organization.deletion_request": [
    "finalDeletionSupported",
    "reasonCode",
    "suspended",
  ],
  "admin.organization.deletion_request.cancel": ["cancelled"],
  "admin.organization.reactivate": ["suspensionCleared"],
  "admin.organization.suspend": ["reasonCode"],
  "admin.organization.update": ["nameChanged", "slugChanged"],
  "admin.rag_policy.change_request.approve": [
    "allowedEmbeddingProviderModelCount",
    "assignedKnowledgeBaseCounts",
    "changedFields",
    "dataResidencyTagCount",
    "enabledTierCount",
    "externalVectorStore",
    "physicalVectorIsolation",
    "requesterSameAsApprover",
    "source",
  ],
  "admin.rag_policy.change_request.create": [
    "allowedEmbeddingProviderModelCount",
    "assignedKnowledgeBaseCounts",
    "changedFields",
    "dataResidencyTagCount",
    "enabledTierCount",
    "evidenceSummary",
    "externalVectorStore",
    "justificationCode",
    "physicalVectorIsolation",
    "source",
  ],
  "admin.rag_policy.change_request.reject": ["changedFields", "reasonCode"],
  "admin.rag_policy.update": [
    "allowedEmbeddingProviderModelCount",
    "assignedKnowledgeBaseCounts",
    "changedFields",
    "dataResidencyTagCount",
    "enabledTierCount",
    "externalVectorStore",
    "physicalVectorIsolation",
    "source",
  ],
  "admin.secret_rotation.rewrap": [
    "keyMaterialReturned",
    "localMfa",
    "managedSecrets",
    "mode",
    "rawSecretValuesReturned",
    "schema",
    "scope",
    "secretRefsReturned",
    "status",
    "totpSecretsReturned",
    "warningCount",
  ],
  "admin.sso_oidc.deprovision": [
    "credentialRevocation",
    "issuerHost",
    "status",
    "subjectHash",
    "subjectLength",
  ],
  "admin.sso_settings.update": [
    "adminGroupCount",
    "clientIdConfigured",
    "configurationSource",
    "enabled",
    "groupClaim",
    "groupMappingCount",
    "issuerHost",
    "providerPreset",
    "resourceId",
    "resourceType",
    "workspaceGroupMappingCount",
    "workspaceGroupPrefixConfigured",
  ],
  "agent.archive": ["workspaceId"],
  "agent.clone": [
    "baseModelId",
    "knowledgeBindingsCopied",
    "sourceAgentId",
    "workspaceId",
  ],
  "agent.create": [
    "baseModelId",
    "memoryMode",
    "parameterKeys",
    "safetyConfigured",
    "workspaceId",
  ],
  "agent.customization_policy.update": ["enabledControls", "workspaceId"],
  "agent.export": ["baseModelId", "bindingCounts", "workspaceId"],
  "agent.import": [
    "baseModelId",
    "bindingCounts",
    "parameterKeys",
    "workspaceId",
  ],
  "agent.knowledge_binding.update": ["created", "enabled", "knowledgeBaseId"],
  "agent.preferences.clear": ["workspaceId"],
  "agent.preferences.update": ["configuredFields", "workspaceId"],
  "agent.tool_binding.update": [
    "approvalRequired",
    "created",
    "enabled",
    "importedOperation",
    "toolId",
  ],
  "agent.update": [
    "changedFields",
    "memoryMode",
    "parameterKeys",
    "safetyConfigured",
    "workspaceId",
  ],
  "agent.version.publish": [
    "agentId",
    "baseModelId",
    "channel",
    "version",
    "workspaceId",
  ],
  "agent.version.rollback": ["baseModelId", "versionId", "workspaceId"],
  "billing.entitlements_reconciled": [
    "afterWarnings",
    "beforeWarnings",
    "billingPlanConfigured",
    "createdQuotaCount",
    "planCode",
    "planStatus",
    "unchangedQuotaCount",
    "updatedQuotaCount",
    "warnings",
  ],
  "billing.external_event_ignored": ["eventType", "provider", "reason"],
  "billing.external_event_synced": [
    "eventType",
    "hasInvoice",
    "hasSubscription",
    "provider",
    "status",
  ],
  "billing.lifecycle_enforced": [
    "action",
    "billingPlanConfigured",
    "newStatus",
    "previousStatus",
    "statusChanged",
    "warnings",
  ],
  "billing.plan_applied": [
    "code",
    "quotaIds",
    "quotaTemplateCount",
    "source",
    "status",
  ],
  "device_authorization.create": ["scopeCount"],
  "device_authorization.refresh": ["scopeCount"],
  "device_authorization.revoke": [],
  "delegated_oauth.connect": [
    "connectorType",
    "providerAccountHash",
    "providerId",
    "scopeCount",
    "workspaceId",
  ],
  "delegated_oauth.refresh": [
    "connectorType",
    "errorCode",
    "providerAccountHash",
    "providerId",
    "scopeCount",
    "workspaceId",
  ],
  "delegated_oauth.revoke": [
    "connectorType",
    "providerAccountHash",
    "providerId",
    "providerRevocationStatus",
    "workspaceId",
  ],
  "governance.data_deletion.execute": [
    "counts",
    "knowledgeBaseId",
    "workspaceId",
  ],
  "governance.data_export.execute": [
    "counts",
    "includeContent",
    "includeObjectBytes",
    "scope",
    "warningCount",
  ],
  "governance.data_export.package.create": [
    "contentType",
    "counts",
    "includeContent",
    "includeObjectBytes",
    "objectKeyHash",
    "packageId",
    "rawObjectKeyReturned",
    "scope",
    "sha256",
    "sizeBytes",
    "warningCount",
  ],
  "governance.data_export.package.delete": [
    "contentType",
    "objectKeyHash",
    "packageContentReturned",
    "packageId",
    "rawObjectKeyReturned",
  ],
  "governance.retention.enforce": [
    "auditLogRetentionDays",
    "cleanedBrowserAutomationJobCount",
    "cleanedVoiceArtifactUsageEventCount",
    "cutoffAt",
    "deletedAuditLogCount",
    "deletedBrowserAutomationArtifactCount",
    "deletedDataExportPackageCount",
    "deletedFileObjectBytes",
    "deletedFileObjectCount",
    "deletedRunEventCount",
    "deletedVoiceArtifactCount",
    "missingDataExportPackageCount",
    "missingFileObjectCount",
    "missingVoiceArtifactCount",
    "runEventCompactionLimitReached",
    "runEventCutoffAt",
    "runEventRetentionDays",
  ],
  "governance.retention.update": [
    "auditLogRetentionDays",
    "fileRetentionDays",
    "runEventRetentionDays",
    "userOverrideCount",
    "workspaceOverrideCount",
  ],
  "model.capabilities.update": ["providerId"],
  "model.enabled.update": ["providerId"],
  "model.pricing.update": ["priceFields", "providerId"],
  "model.request": [],
  "prompt_template.create": ["tagCount", "visibility", "workspaceId"],
  "prompt_template.delete": ["visibility", "workspaceId"],
  "prompt_template.update": ["changedFields", "tagCount", "visibility"],
  "provider.create": ["credentialConfigured", "enabled", "providerType"],
  "provider.model.delete": ["model", "status"],
  "provider.model.pull": ["model", "status"],
  "provider.models.sync": [
    "error",
    "modelCount",
    "providerType",
    "unavailableModelCount",
  ],
  "provider.update": ["credentialConfigured", "enabled", "modelIdCount"],
  "quota.create": ["limit", "metric", "resetInterval", "scopeId", "scopeType"],
  "quota.delete": ["limit", "metric", "resetInterval", "scopeId", "scopeType"],
  "quota.update": [
    "changedLimit",
    "changedResetInterval",
    "limit",
    "metric",
    "resetInterval",
    "resetUsage",
    "scopeId",
    "scopeType",
  ],
  "session.create": ["scopeCount", "ttlHours"],
  "session.revoke": ["exceptSessionId", "targetUserId"],
  "user.disable": [
    "credentialRevocation",
    "revokedApiKeyCount",
    "revokedOwnedSupportSessionCount",
    "revokedSessionCount",
  ],
  "user.profile.update": [
    "emailChanged",
    "localPasswordCredentialEmailUpdated",
    "nameChanged",
  ],
  "user.role.update": ["credentialRevocation", "previousRole", "role"],
  "web_search.configuration.update": [
    "allowedDomainCount",
    "blockedDomainCount",
    "credentialConfigured",
    "enabled",
    "provider",
  ],
  "webhook.bulk_disable": [],
  "webhook.create": [],
  "webhook.delivery": [],
  "webhook.disable": [],
  "webhook.test": [],
  "workspace.archive": ["archivedAt"],
  "workspace.create": ["slug"],
  "workspace.default_agent.update": ["agentId"],
  "workspace.export": ["counts"],
} as const;
