import type { UsageMetricCode as ContractUsageMetricCode } from "@romeo/contracts";

import type { UsageEvent } from "./domain/entities";
import {
  defineUsageMetric as define,
  type UsageMetricDefinition,
} from "./usage-taxonomy-types";

export type {
  UsageAggregation,
  UsageMeasurement,
  UsageMetricCategory,
  UsageMetricDefinition,
  UsageOverlapPolicy,
} from "./usage-taxonomy-types";

/**
 * Canonical metrics for new writes. Historical database rows remain readable,
 * but every create/update crosses assertUsageEventTaxonomy at the repository
 * boundary so metric, unit, source type, and quantity cannot drift again.
 */
export const USAGE_METRIC_DEFINITIONS = Object.freeze({
  "audio.input_byte": define({
    category: "audio",
    unit: "byte",
    sourceTypes: ["voice"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "audio.input_second": define({
    category: "audio",
    unit: "second",
    sourceTypes: ["voice"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "exclusive",
    billable: true,
  }),
  "audio.output_character": define({
    category: "audio",
    unit: "character",
    sourceTypes: ["voice"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "audio.output_second": define({
    category: "audio",
    unit: "second",
    sourceTypes: ["voice"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "exclusive",
    billable: true,
  }),
  "chat.message.feedback": define({
    category: "activity",
    unit: "feedback",
    sourceTypes: ["chat"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "compute.cpu_millisecond": define({
    category: "compute",
    unit: "cpu_millisecond",
    sourceTypes: ["tool"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "exclusive",
    billable: true,
  }),
  "compute.memory_byte_millisecond": define({
    category: "compute",
    unit: "byte_millisecond",
    sourceTypes: ["tool"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "exclusive",
    billable: true,
  }),
  "file.upload.pipeline_duration": define({
    category: "latency",
    unit: "millisecond",
    sourceTypes: ["storage"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "non_additive",
    billable: false,
  }),
  "image.cost.micro_usd": define({
    category: "cost",
    unit: "micro_usd",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "estimated",
    overlapPolicy: "exclusive",
    billable: true,
  }),
  "image.generated": define({
    category: "image",
    unit: "image",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "exclusive",
    billable: true,
  }),
  "image.input": define({
    category: "image",
    unit: "image",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "exclusive",
    billable: true,
  }),
  "llm.cached_input_token.reported": define({
    category: "text_token",
    unit: "token",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "reported",
    overlapPolicy: "component_of_total",
    billable: false,
  }),
  "llm.input_token.estimated": define({
    category: "text_token",
    unit: "token",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "estimated",
    overlapPolicy: "non_additive",
    billable: false,
  }),
  "llm.input_token.reported": define({
    category: "text_token",
    unit: "token",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "reported",
    overlapPolicy: "component_of_total",
    billable: true,
  }),
  "llm.output_token.estimated": define({
    category: "text_token",
    unit: "token",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "estimated",
    overlapPolicy: "non_additive",
    billable: false,
  }),
  "llm.output_token.reported": define({
    category: "text_token",
    unit: "token",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "reported",
    overlapPolicy: "component_of_total",
    billable: true,
  }),
  "llm.reasoning_token.reported": define({
    category: "text_token",
    unit: "token",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "reported",
    overlapPolicy: "component_of_total",
    billable: false,
  }),
  "llm.total_token.reported": define({
    category: "text_token",
    unit: "token",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "reported",
    overlapPolicy: "non_additive",
    billable: false,
  }),
  "provider.error": define({
    category: "activity",
    unit: "error",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "queue.wait": define({
    category: "latency",
    unit: "millisecond",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "non_additive",
    billable: false,
  }),
  "retrieval.unit": define({
    category: "retrieval",
    unit: "retrieval_unit",
    sourceTypes: ["retrieval"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "exclusive",
    billable: true,
  }),
  "run.cancelled": define({
    category: "activity",
    unit: "run",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "run.completed": define({
    category: "activity",
    unit: "run",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "run.duration": define({
    category: "latency",
    unit: "millisecond",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "non_additive",
    billable: false,
  }),
  "run.failed": define({
    category: "activity",
    unit: "run",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "run.output_throughput": define({
    category: "latency",
    unit: "token_per_second",
    sourceTypes: ["run"],
    aggregation: "maximum",
    measurement: "measured",
    overlapPolicy: "non_additive",
    billable: false,
  }),
  "run.recovery": define({
    category: "activity",
    unit: "recovery",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "run.started": define({
    category: "activity",
    unit: "run",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "run.time_to_first_token": define({
    category: "latency",
    unit: "millisecond",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "non_additive",
    billable: false,
  }),
  "sse.connection": define({
    category: "activity",
    unit: "connection",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "sse.disconnect": define({
    category: "activity",
    unit: "connection",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "sse.reconnect": define({
    category: "activity",
    unit: "connection",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "storage.byte": define({
    category: "storage",
    unit: "byte",
    sourceTypes: ["storage"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "exclusive",
    billable: true,
  }),
  "storage.embedding_indexed": define({
    category: "retrieval",
    unit: "embedding",
    sourceTypes: ["storage"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "exclusive",
    billable: true,
  }),
  "storage.source_completed": define({
    category: "storage",
    unit: "byte",
    sourceTypes: ["storage"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "non_additive",
    billable: false,
  }),
  "storage.source_deleted": define({
    category: "storage",
    unit: "byte",
    sourceTypes: ["storage"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "non_additive",
    billable: false,
  }),
  "storage.source_extracted": define({
    category: "storage",
    unit: "byte",
    sourceTypes: ["storage"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "non_additive",
    billable: false,
  }),
  "storage.source_registered": define({
    category: "storage",
    unit: "byte",
    sourceTypes: ["storage"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "non_additive",
    billable: false,
  }),
  "storage.source_reindexed": define({
    category: "storage",
    unit: "byte",
    sourceTypes: ["storage"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "non_additive",
    billable: false,
  }),
  "tool.call.failure": define({
    category: "activity",
    unit: "call",
    sourceTypes: ["tool"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "tool.call.success": define({
    category: "activity",
    unit: "call",
    sourceTypes: ["tool"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "trace.span": define({
    category: "latency",
    unit: "millisecond",
    sourceTypes: ["storage"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "non_additive",
    billable: false,
  }),
  "video.input_second": define({
    category: "video",
    unit: "second",
    sourceTypes: ["run"],
    aggregation: "sum",
    measurement: "measured",
    overlapPolicy: "exclusive",
    billable: true,
  }),
  "voice.message.generated": define({
    category: "activity",
    unit: "event",
    sourceTypes: ["voice"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "voice.preview.generated": define({
    category: "activity",
    unit: "event",
    sourceTypes: ["voice"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "voice.transcription.generated": define({
    category: "activity",
    unit: "event",
    sourceTypes: ["voice"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "web.search.request": define({
    category: "activity",
    unit: "request",
    sourceTypes: ["retrieval"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
  "web.url.fetch": define({
    category: "activity",
    unit: "url",
    sourceTypes: ["retrieval"],
    aggregation: "sum",
    measurement: "activity",
    overlapPolicy: "exclusive",
    billable: false,
  }),
} as const satisfies Record<ContractUsageMetricCode, UsageMetricDefinition>);

export type UsageMetricCode = ContractUsageMetricCode;
export type UsageUnit<M extends UsageMetricCode> =
  (typeof USAGE_METRIC_DEFINITIONS)[M]["unit"];
export type UsageSourceType<M extends UsageMetricCode> =
  (typeof USAGE_METRIC_DEFINITIONS)[M]["sourceTypes"][number];

export type RecordedUsageEventInput<M extends UsageMetricCode> = Omit<
  UsageEvent,
  "createdAt" | "id" | "metric" | "sourceType" | "unit"
> & {
  metric: M;
  sourceType: UsageSourceType<M>;
  unit: UsageUnit<M>;
};
