import type { ToolConnectorType } from "./tools";

export type ToolConnectorImplementationStatus =
  | "implemented"
  | "separate_api"
  | "planned";

export type ToolConnectorCreationMode =
  | "built_in_registry"
  | "mcp_manifest"
  | "openapi_import"
  | "webhook_registration"
  | "workflow_browser_automation"
  | "not_available";

export type ToolConnectorExecutionBoundary =
  | "bounded_in_process"
  | "external_worker_dispatch"
  | "workflow_worker_bridge"
  | "not_available";

export type ToolConnectorCredentialSource =
  | "none"
  | "managed_secret_ref"
  | "oauth2_client_credentials";

export interface ToolConnectorCatalogEntry {
  type: ToolConnectorType;
  displayName: string;
  description: string;
  implementationStatus: ToolConnectorImplementationStatus;
  creationMode: ToolConnectorCreationMode;
  executionBoundary: ToolConnectorExecutionBoundary;
  operationDiscovery:
    | "static_registry"
    | "mcp_manifest"
    | "openapi_import"
    | "webhook_registration"
    | "planned";
  supportsAuthConfig: boolean;
  supportsNetworkPolicy: boolean;
  supportsModelToolInjection: boolean;
  credentialSources: ToolConnectorCredentialSource[];
  requiredScopes: string[];
  securityControls: string[];
  blockedReasons: string[];
}

export interface ToolConnectorCatalogReport {
  schemaVersion: "romeo.tool-connector-catalog.v1";
  entries: ToolConnectorCatalogEntry[];
  redaction: {
    rawConnectorConfigsReturned: false;
    rawEndpointUrlsReturned: false;
    rawSecretRefsReturned: false;
    secretValuesReturned: false;
  };
}

export const toolConnectorCatalog: ToolConnectorCatalogEntry[] = [
  {
    type: "built_in",
    displayName: "Built-in tools",
    description:
      "Reviewed in-process tools from the Romeo tool registry, such as calculator and date/time.",
    implementationStatus: "implemented",
    creationMode: "built_in_registry",
    executionBoundary: "bounded_in_process",
    operationDiscovery: "static_registry",
    supportsAuthConfig: false,
    supportsNetworkPolicy: false,
    supportsModelToolInjection: true,
    credentialSources: ["none"],
    requiredScopes: ["tools:use"],
    securityControls: [
      "fixed registry",
      "bounded input and output schemas",
      "agent binding authorization",
      "approval policy enforcement",
      "metadata-only tool-call records",
    ],
    blockedReasons: [],
  },
  {
    type: "openapi",
    displayName: "OpenAPI imported operations",
    description:
      "Admin-imported OpenAPI operations that can be previewed, approved, queued, and executed through the external worker boundary.",
    implementationStatus: "implemented",
    creationMode: "openapi_import",
    executionBoundary: "external_worker_dispatch",
    operationDiscovery: "openapi_import",
    supportsAuthConfig: true,
    supportsNetworkPolicy: true,
    supportsModelToolInjection: true,
    credentialSources: [
      "none",
      "managed_secret_ref",
      "oauth2_client_credentials",
    ],
    requiredScopes: ["tools:manage"],
    securityControls: [
      "disabled by default",
      "operation activation required",
      "host allowlist required for execution",
      "managed secret refs only",
      "optional encrypted object-store payload handoff",
      "active worker lease required for payload readback",
      "response bodies omitted from readback",
    ],
    blockedReasons: [],
  },
  {
    type: "mcp",
    displayName: "MCP connector",
    description:
      "Reviewed Streamable HTTP MCP server operations imported from an admin-provided static tool manifest and executed through the external worker boundary.",
    implementationStatus: "implemented",
    creationMode: "mcp_manifest",
    executionBoundary: "external_worker_dispatch",
    operationDiscovery: "mcp_manifest",
    supportsAuthConfig: true,
    supportsNetworkPolicy: true,
    supportsModelToolInjection: true,
    credentialSources: [
      "none",
      "managed_secret_ref",
      "oauth2_client_credentials",
    ],
    requiredScopes: ["tools:manage"],
    securityControls: [
      "disabled by default",
      "static reviewed tool manifest",
      "Streamable HTTP transport only",
      "stdio and local command transports are not supported",
      "host allowlist derived from the reviewed server URL",
      "managed secret refs only",
      "external dispatch worker required for execution",
      "JSON-RPC tools/call envelope generated by the worker",
      "request and response bodies omitted from audits",
    ],
    blockedReasons: [],
  },
  {
    type: "webhook",
    displayName: "Webhook tool connector",
    description:
      "Admin-created single-operation HTTPS webhook connector that executes through the external worker boundary.",
    implementationStatus: "implemented",
    creationMode: "webhook_registration",
    executionBoundary: "external_worker_dispatch",
    operationDiscovery: "webhook_registration",
    supportsAuthConfig: true,
    supportsNetworkPolicy: true,
    supportsModelToolInjection: true,
    credentialSources: ["none", "managed_secret_ref"],
    requiredScopes: ["tools:manage"],
    securityControls: [
      "disabled by default",
      "single POST operation",
      "HTTPS URL validation",
      "host allowlist derived from the reviewed target URL",
      "optional managed secret refs only",
      "external dispatch worker required for execution",
      "request and response bodies omitted from audits",
    ],
    blockedReasons: [],
  },
  {
    type: "browser",
    displayName: "Browser automation",
    description:
      "Browser automation is implemented through workflow browser-task APIs and a separate external runner, not through the imported tool connector table.",
    implementationStatus: "separate_api",
    creationMode: "workflow_browser_automation",
    executionBoundary: "workflow_worker_bridge",
    operationDiscovery: "planned",
    supportsAuthConfig: false,
    supportsNetworkPolicy: true,
    supportsModelToolInjection: false,
    credentialSources: ["none"],
    requiredScopes: ["workflows:write"],
    securityControls: [
      "approved workflow step required",
      "external HTTPS runner required",
      "artifact readback uses server-issued URLs",
      "live runner sandbox evidence required for deployment claims",
    ],
    blockedReasons: ["use_browser_automation_workflow_api"],
  },
  {
    type: "enterprise",
    displayName: "Enterprise connector",
    description:
      "Future customer-specific enterprise tool connector package with reviewed adapter, egress, and evidence contracts.",
    implementationStatus: "planned",
    creationMode: "not_available",
    executionBoundary: "not_available",
    operationDiscovery: "planned",
    supportsAuthConfig: false,
    supportsNetworkPolicy: true,
    supportsModelToolInjection: false,
    credentialSources: ["managed_secret_ref"],
    requiredScopes: ["tools:manage"],
    securityControls: [
      "must pass connector intake",
      "must stay out of process when it can reach customer systems",
      "must provide adapter acceptance and live egress evidence",
      "must keep secrets and response bodies out of readback",
    ],
    blockedReasons: ["enterprise_tool_connector_runtime_not_implemented"],
  },
];

export function toolConnectorCatalogReport(): ToolConnectorCatalogReport {
  return {
    schemaVersion: "romeo.tool-connector-catalog.v1",
    entries: toolConnectorCatalog,
    redaction: {
      rawConnectorConfigsReturned: false,
      rawEndpointUrlsReturned: false,
      rawSecretRefsReturned: false,
      secretValuesReturned: false,
    },
  };
}
