export {
  AwsSecretValueResolver,
  AzureSecretValueResolver,
  CloudSecretValueResolver,
  GcpSecretValueResolver,
  type AwsSecretsManagerResolverOptions as AwsSecretValueResolverOptions,
  type AwsSecretsManagerSdkClient,
  type AwsSecretsManagerSdkClientFactory,
  type AzureKeyVaultResolverOptions as AzureSecretValueResolverOptions,
  type AzureKeyVaultSdkClient,
  type AzureKeyVaultSdkClientFactory,
  type GcpSecretManagerResolverOptions as GcpSecretValueResolverOptions,
  type GcpSecretManagerSdkClient,
  type GcpSecretManagerSdkClientFactory,
} from "@romeo/secrets";
