# Generated by scripts/generate-python-sdk.mjs. Do not edit by hand.

OPERATIONS = {
    "get_access_review": {
        "name": "get_access_review",
        "method": "GET",
        "path": "/api/v1/access-review",
        "summary": "List resource grants for access review"
    },
    "get_access_review_csv": {
        "name": "get_access_review_csv",
        "method": "GET",
        "path": "/api/v1/access-review.csv",
        "summary": "Export resource grants for access review as CSV"
    },
    "get_access_review_report": {
        "name": "get_access_review_report",
        "method": "GET",
        "path": "/api/v1/access-review/report",
        "summary": "Export a redacted enterprise access review report"
    },
    "get_access_review_report_csv": {
        "name": "get_access_review_report_csv",
        "method": "GET",
        "path": "/api/v1/access-review/report.csv",
        "summary": "Export a redacted enterprise access review report as CSV"
    },
    "get_admin_abuse_controls": {
        "name": "get_admin_abuse_controls",
        "method": "GET",
        "path": "/api/v1/admin/abuse-controls",
        "summary": "Get organization abuse controls and entitlement posture"
    },
    "patch_admin_abuse_controls": {
        "name": "patch_admin_abuse_controls",
        "method": "PATCH",
        "path": "/api/v1/admin/abuse-controls",
        "summary": "Update organization suspension, entitlement, and kill-switch policy"
    },
    "get_admin_alert_firing_posture": {
        "name": "get_admin_alert_firing_posture",
        "method": "GET",
        "path": "/api/v1/admin/alert-firing/posture",
        "summary": "Report sanitized live alert-firing evidence posture"
    },
    "get_admin_analytics_authz_posture": {
        "name": "get_admin_analytics_authz_posture",
        "method": "GET",
        "path": "/api/v1/admin/analytics/authz-posture",
        "summary": "Read target analytics authorization evidence posture"
    },
    "get_admin_analytics_summary": {
        "name": "get_admin_analytics_summary",
        "method": "GET",
        "path": "/api/v1/admin/analytics/summary",
        "summary": "Summarize admin quality, usage, provider, tool, and job analytics"
    },
    "get_admin_analytics_summary_csv": {
        "name": "get_admin_analytics_summary_csv",
        "method": "GET",
        "path": "/api/v1/admin/analytics/summary.csv",
        "summary": "Export redacted admin analytics summary as CSV"
    },
    "get_admin_audit_integrity_posture": {
        "name": "get_admin_audit_integrity_posture",
        "method": "GET",
        "path": "/api/v1/admin/audit-integrity/posture",
        "summary": "Get metadata-only audit integrity and SIEM export posture"
    },
    "get_admin_auth_providers_catalog": {
        "name": "get_admin_auth_providers_catalog",
        "method": "GET",
        "path": "/api/v1/admin/auth-providers/catalog",
        "summary": "List enterprise authentication provider catalog entries"
    },
    "get_admin_auth_providers_settings": {
        "name": "get_admin_auth_providers_settings",
        "method": "GET",
        "path": "/api/v1/admin/auth-providers/settings",
        "summary": "Get sanitized global and org authentication provider settings"
    },
    "patch_admin_auth_providers_settings": {
        "name": "patch_admin_auth_providers_settings",
        "method": "PATCH",
        "path": "/api/v1/admin/auth-providers/settings",
        "summary": "Update global or org authentication provider settings"
    },
    "post_admin_auth_providers_settings_test": {
        "name": "post_admin_auth_providers_settings_test",
        "method": "POST",
        "path": "/api/v1/admin/auth-providers/settings/test",
        "summary": "Test an authentication provider connection without exposing secrets"
    },
    "get_admin_billing_operations_posture": {
        "name": "get_admin_billing_operations_posture",
        "method": "GET",
        "path": "/api/v1/admin/billing/operations-posture",
        "summary": "Get metadata-only billing operations cadence and alert posture"
    },
    "get_admin_browser_automation_posture": {
        "name": "get_admin_browser_automation_posture",
        "method": "GET",
        "path": "/api/v1/admin/browser-automation/posture",
        "summary": "Get sanitized browser automation worker, queue, artifact, and live-evidence posture"
    },
    "get_admin_ci_governance_posture": {
        "name": "get_admin_ci_governance_posture",
        "method": "GET",
        "path": "/api/v1/admin/ci-governance/posture",
        "summary": "Report sanitized CI governance posture"
    },
    "get_admin_data_connectors_posture": {
        "name": "get_admin_data_connectors_posture",
        "method": "GET",
        "path": "/api/v1/admin/data-connectors/posture",
        "summary": "Get sanitized data connector runtime, worker, sync, and live-evidence posture"
    },
    "get_admin_delegated_oauth_posture": {
        "name": "get_admin_delegated_oauth_posture",
        "method": "GET",
        "path": "/api/v1/admin/delegated-oauth/posture",
        "summary": "Get sanitized delegated OAuth provider and connection health posture"
    },
    "post_admin_directory_sync": {
        "name": "post_admin_directory_sync",
        "method": "POST",
        "path": "/api/v1/admin/directory-sync",
        "summary": "Preview or apply destructive directory lifecycle sync changes with redacted output"
    },
    "get_admin_edge_security_posture": {
        "name": "get_admin_edge_security_posture",
        "method": "GET",
        "path": "/api/v1/admin/edge-security/posture",
        "summary": "Get sanitized edge, ingress, WAF, and security-header posture"
    },
    "get_admin_ga_evidence_posture": {
        "name": "get_admin_ga_evidence_posture",
        "method": "GET",
        "path": "/api/v1/admin/ga/evidence-posture",
        "summary": "Report sanitized GA evidence posture from configured checklist, preflight, target-plan, and bundle files"
    },
    "get_admin_identity_live_posture": {
        "name": "get_admin_identity_live_posture",
        "method": "GET",
        "path": "/api/v1/admin/identity/live-posture",
        "summary": "Read target identity live-evidence posture"
    },
    "get_admin_impersonation_requests": {
        "name": "get_admin_impersonation_requests",
        "method": "GET",
        "path": "/api/v1/admin/impersonation/requests",
        "summary": "List support impersonation approval requests"
    },
    "post_admin_impersonation_requests": {
        "name": "post_admin_impersonation_requests",
        "method": "POST",
        "path": "/api/v1/admin/impersonation/requests",
        "summary": "Create a support impersonation approval request"
    },
    "post_admin_impersonation_requests_requestid_approve": {
        "name": "post_admin_impersonation_requests_requestid_approve",
        "method": "POST",
        "path": "/api/v1/admin/impersonation/requests/{requestId}/approve",
        "summary": "Approve a support impersonation request and mint the session"
    },
    "post_admin_impersonation_requests_requestid_reject": {
        "name": "post_admin_impersonation_requests_requestid_reject",
        "method": "POST",
        "path": "/api/v1/admin/impersonation/requests/{requestId}/reject",
        "summary": "Reject a pending support impersonation request"
    },
    "get_admin_impersonation_sessions": {
        "name": "get_admin_impersonation_sessions",
        "method": "GET",
        "path": "/api/v1/admin/impersonation/sessions",
        "summary": "List audited support impersonation session reports"
    },
    "post_admin_impersonation_sessions": {
        "name": "post_admin_impersonation_sessions",
        "method": "POST",
        "path": "/api/v1/admin/impersonation/sessions",
        "summary": "Create an audited short-lived support impersonation session"
    },
    "post_admin_impersonation_sessions_sessionid_revoke": {
        "name": "post_admin_impersonation_sessions_sessionid_revoke",
        "method": "POST",
        "path": "/api/v1/admin/impersonation/sessions/{sessionId}/revoke",
        "summary": "Revoke an audited support impersonation session"
    },
    "get_admin_kubernetes_posture": {
        "name": "get_admin_kubernetes_posture",
        "method": "GET",
        "path": "/api/v1/admin/kubernetes/posture",
        "summary": "Report sanitized Kubernetes live-evidence posture"
    },
    "get_admin_migrations_drill_posture": {
        "name": "get_admin_migrations_drill_posture",
        "method": "GET",
        "path": "/api/v1/admin/migrations/drill-posture",
        "summary": "Get metadata-only failed migration drill posture"
    },
    "get_admin_network_partition_posture": {
        "name": "get_admin_network_partition_posture",
        "method": "GET",
        "path": "/api/v1/admin/network/partition-posture",
        "summary": "Get metadata-only network partition drill posture"
    },
    "get_admin_notification_policy": {
        "name": "get_admin_notification_policy",
        "method": "GET",
        "path": "/api/v1/admin/notification-policy",
        "summary": "Inspect organization notification delivery policy"
    },
    "patch_admin_notification_policy": {
        "name": "patch_admin_notification_policy",
        "method": "PATCH",
        "path": "/api/v1/admin/notification-policy",
        "summary": "Update organization notification delivery policy"
    },
    "get_admin_notifications_adapter_live_posture": {
        "name": "get_admin_notifications_adapter_live_posture",
        "method": "GET",
        "path": "/api/v1/admin/notifications/adapter-live-posture",
        "summary": "Read target notification adapter live-evidence posture"
    },
    "get_admin_organizations": {
        "name": "get_admin_organizations",
        "method": "GET",
        "path": "/api/v1/admin/organizations",
        "summary": "List tenant organizations for global administration"
    },
    "post_admin_organizations": {
        "name": "post_admin_organizations",
        "method": "POST",
        "path": "/api/v1/admin/organizations",
        "summary": "Provision a tenant organization with a default workspace"
    },
    "get_admin_organizations_orgid": {
        "name": "get_admin_organizations_orgid",
        "method": "GET",
        "path": "/api/v1/admin/organizations/{orgId}",
        "summary": "Get tenant organization lifecycle posture"
    },
    "patch_admin_organizations_orgid": {
        "name": "patch_admin_organizations_orgid",
        "method": "PATCH",
        "path": "/api/v1/admin/organizations/{orgId}",
        "summary": "Update tenant organization metadata"
    },
    "post_admin_organizations_orgid_deletion_finalization_evidence": {
        "name": "post_admin_organizations_orgid_deletion_finalization_evidence",
        "method": "POST",
        "path": "/api/v1/admin/organizations/{orgId}/deletion-finalization-evidence",
        "summary": "Record reviewed metadata-only tenant deletion finalization evidence"
    },
    "get_admin_organizations_orgid_deletion_finalization_preview": {
        "name": "get_admin_organizations_orgid_deletion_finalization_preview",
        "method": "GET",
        "path": "/api/v1/admin/organizations/{orgId}/deletion-finalization-preview",
        "summary": "Preview governed tenant deletion finalization readiness and required evidence"
    },
    "post_admin_organizations_orgid_deletion_finalization_execute": {
        "name": "post_admin_organizations_orgid_deletion_finalization_execute",
        "method": "POST",
        "path": "/api/v1/admin/organizations/{orgId}/deletion-finalization/execute",
        "summary": "Execute final governed tenant deletion after evidence approval"
    },
    "post_admin_organizations_orgid_deletion_request": {
        "name": "post_admin_organizations_orgid_deletion_request",
        "method": "POST",
        "path": "/api/v1/admin/organizations/{orgId}/deletion-request",
        "summary": "Request governed tenant deletion and suspend the tenant"
    },
    "post_admin_organizations_orgid_deletion_request_cancel": {
        "name": "post_admin_organizations_orgid_deletion_request_cancel",
        "method": "POST",
        "path": "/api/v1/admin/organizations/{orgId}/deletion-request/cancel",
        "summary": "Cancel a governed tenant deletion request"
    },
    "post_admin_organizations_orgid_reactivate": {
        "name": "post_admin_organizations_orgid_reactivate",
        "method": "POST",
        "path": "/api/v1/admin/organizations/{orgId}/reactivate",
        "summary": "Reactivate a suspended tenant organization"
    },
    "post_admin_organizations_orgid_suspend": {
        "name": "post_admin_organizations_orgid_suspend",
        "method": "POST",
        "path": "/api/v1/admin/organizations/{orgId}/suspend",
        "summary": "Suspend a tenant organization through abuse controls"
    },
    "get_admin_postgres_operational_posture": {
        "name": "get_admin_postgres_operational_posture",
        "method": "GET",
        "path": "/api/v1/admin/postgres/operational-posture",
        "summary": "Report sanitized Postgres scale and operations posture for admins"
    },
    "get_admin_providers_outage_posture": {
        "name": "get_admin_providers_outage_posture",
        "method": "GET",
        "path": "/api/v1/admin/providers/outage-posture",
        "summary": "Get metadata-only provider outage drill posture"
    },
    "get_admin_rag_policy": {
        "name": "get_admin_rag_policy",
        "method": "GET",
        "path": "/api/v1/admin/rag/policy",
        "summary": "Get org RAG policy"
    },
    "patch_admin_rag_policy": {
        "name": "patch_admin_rag_policy",
        "method": "PATCH",
        "path": "/api/v1/admin/rag/policy",
        "summary": "Update org RAG policy"
    },
    "get_admin_rag_policy_change_request": {
        "name": "get_admin_rag_policy_change_request",
        "method": "GET",
        "path": "/api/v1/admin/rag/policy/change-request",
        "summary": "Get the latest org RAG policy change request"
    },
    "post_admin_rag_policy_change_requests": {
        "name": "post_admin_rag_policy_change_requests",
        "method": "POST",
        "path": "/api/v1/admin/rag/policy/change-requests",
        "summary": "Create a governed org RAG policy change request"
    },
    "post_admin_rag_policy_change_requests_requestid_approve": {
        "name": "post_admin_rag_policy_change_requests_requestid_approve",
        "method": "POST",
        "path": "/api/v1/admin/rag/policy/change-requests/{requestId}/approve",
        "summary": "Approve and apply a governed org RAG policy change request"
    },
    "post_admin_rag_policy_change_requests_requestid_reject": {
        "name": "post_admin_rag_policy_change_requests_requestid_reject",
        "method": "POST",
        "path": "/api/v1/admin/rag/policy/change-requests/{requestId}/reject",
        "summary": "Reject a governed org RAG policy change request"
    },
    "get_admin_rag_posture": {
        "name": "get_admin_rag_posture",
        "method": "GET",
        "path": "/api/v1/admin/rag/posture",
        "summary": "Get sanitized RAG and vector posture"
    },
    "post_admin_rag_replay": {
        "name": "post_admin_rag_replay",
        "method": "POST",
        "path": "/api/v1/admin/rag/replay",
        "summary": "Replay tiered retrieval cases with metadata-only metrics"
    },
    "post_admin_rag_replay_compare": {
        "name": "post_admin_rag_replay_compare",
        "method": "POST",
        "path": "/api/v1/admin/rag/replay/compare",
        "summary": "Compare baseline and candidate tiered retrieval replay metrics without raw corpus echo"
    },
    "get_admin_readiness": {
        "name": "get_admin_readiness",
        "method": "GET",
        "path": "/api/v1/admin/readiness",
        "summary": "Get production readiness checks"
    },
    "get_admin_release_readback_posture": {
        "name": "get_admin_release_readback_posture",
        "method": "GET",
        "path": "/api/v1/admin/release-readback/posture",
        "summary": "Report sanitized release readback posture"
    },
    "get_admin_release_security_posture": {
        "name": "get_admin_release_security_posture",
        "method": "GET",
        "path": "/api/v1/admin/release-security/posture",
        "summary": "Report sanitized release security posture"
    },
    "get_admin_secret_rotation_drill_posture": {
        "name": "get_admin_secret_rotation_drill_posture",
        "method": "GET",
        "path": "/api/v1/admin/secret-rotation/drill-posture",
        "summary": "Get metadata-only secret rotation drill posture"
    },
    "post_admin_secret_rotation_rewrap": {
        "name": "post_admin_secret_rotation_rewrap",
        "method": "POST",
        "path": "/api/v1/admin/secret-rotation/rewrap",
        "summary": "Rewrap encrypted local MFA and managed-secret envelopes with the active key"
    },
    "post_admin_secret_rotation_rewrap_preview": {
        "name": "post_admin_secret_rotation_rewrap_preview",
        "method": "POST",
        "path": "/api/v1/admin/secret-rotation/rewrap/preview",
        "summary": "Preview encrypted local MFA and managed-secret envelope rewrap readiness"
    },
    "post_admin_secrets": {
        "name": "post_admin_secrets",
        "method": "POST",
        "path": "/api/v1/admin/secrets",
        "summary": "Store a managed secret and return a one-time ref"
    },
    "get_admin_sso_settings": {
        "name": "get_admin_sso_settings",
        "method": "GET",
        "path": "/api/v1/admin/sso-settings",
        "summary": "Get sanitized SSO settings"
    },
    "patch_admin_sso_settings": {
        "name": "patch_admin_sso_settings",
        "method": "PATCH",
        "path": "/api/v1/admin/sso-settings",
        "summary": "Update sanitized SSO settings"
    },
    "post_admin_sso_settings_test": {
        "name": "post_admin_sso_settings_test",
        "method": "POST",
        "path": "/api/v1/admin/sso-settings/test",
        "summary": "Test sanitized OIDC discovery and JWKS reachability"
    },
    "post_admin_sso_oidc_deprovision": {
        "name": "post_admin_sso_oidc_deprovision",
        "method": "POST",
        "path": "/api/v1/admin/sso/oidc/deprovision",
        "summary": "Disable a user mapped from the active OIDC issuer and subject"
    },
    "get_admin_support_bundle_posture": {
        "name": "get_admin_support_bundle_posture",
        "method": "GET",
        "path": "/api/v1/admin/support-bundle/posture",
        "summary": "Report sanitized support bundle posture"
    },
    "get_admin_target_quality_posture": {
        "name": "get_admin_target_quality_posture",
        "method": "GET",
        "path": "/api/v1/admin/target-quality/posture",
        "summary": "Report sanitized target-quality evidence posture"
    },
    "get_admin_tenant_deletion_purge_evidence_posture": {
        "name": "get_admin_tenant_deletion_purge_evidence_posture",
        "method": "GET",
        "path": "/api/v1/admin/tenant-deletion/purge-evidence-posture",
        "summary": "Get metadata-only tenant purge evidence posture"
    },
    "get_admin_tool_dispatch_posture": {
        "name": "get_admin_tool_dispatch_posture",
        "method": "GET",
        "path": "/api/v1/admin/tool-dispatch/posture",
        "summary": "Get sanitized tool-dispatch worker, queue, payload, and live-evidence posture"
    },
    "get_admin_voice_provider_live_posture": {
        "name": "get_admin_voice_provider_live_posture",
        "method": "GET",
        "path": "/api/v1/admin/voice/provider-live-posture",
        "summary": "Read target voice provider live-evidence posture"
    },
    "get_agent_gallery": {
        "name": "get_agent_gallery",
        "method": "GET",
        "path": "/api/v1/agent-gallery",
        "summary": "List discoverable published agents for a workspace"
    },
    "get_agents": {
        "name": "get_agents",
        "method": "GET",
        "path": "/api/v1/agents",
        "summary": "List agents in a workspace"
    },
    "post_agents": {
        "name": "post_agents",
        "method": "POST",
        "path": "/api/v1/agents",
        "summary": "Create an agent"
    },
    "post_agents_import": {
        "name": "post_agents_import",
        "method": "POST",
        "path": "/api/v1/agents/import",
        "summary": "Import an agent draft from a versioned JSON document"
    },
    "get_agents_agentid": {
        "name": "get_agents_agentid",
        "method": "GET",
        "path": "/api/v1/agents/{agentId}",
        "summary": "Get an agent"
    },
    "patch_agents_agentid": {
        "name": "patch_agents_agentid",
        "method": "PATCH",
        "path": "/api/v1/agents/{agentId}",
        "summary": "Update an agent draft"
    },
    "post_agents_agentid_clone": {
        "name": "post_agents_agentid_clone",
        "method": "POST",
        "path": "/api/v1/agents/{agentId}/clone",
        "summary": "Clone an agent"
    },
    "get_agents_agentid_eval_dashboard": {
        "name": "get_agents_agentid_eval_dashboard",
        "method": "GET",
        "path": "/api/v1/agents/{agentId}/eval-dashboard",
        "summary": "Summarize historical eval runs for an agent"
    },
    "get_agents_agentid_eval_release_candidate_evidence": {
        "name": "get_agents_agentid_eval_release_candidate_evidence",
        "method": "GET",
        "path": "/api/v1/agents/{agentId}/eval-release-candidate-evidence",
        "summary": "Generate metadata-only release-candidate eval evidence for an agent"
    },
    "get_agents_agentid_eval_runs": {
        "name": "get_agents_agentid_eval_runs",
        "method": "GET",
        "path": "/api/v1/agents/{agentId}/eval-runs",
        "summary": "List eval runs for an agent"
    },
    "get_agents_agentid_eval_suites": {
        "name": "get_agents_agentid_eval_suites",
        "method": "GET",
        "path": "/api/v1/agents/{agentId}/eval-suites",
        "summary": "List eval suites for an agent"
    },
    "get_agents_agentid_export": {
        "name": "get_agents_agentid_export",
        "method": "GET",
        "path": "/api/v1/agents/{agentId}/export",
        "summary": "Export an agent draft as a versioned JSON document"
    },
    "get_agents_agentid_knowledge_bases": {
        "name": "get_agents_agentid_knowledge_bases",
        "method": "GET",
        "path": "/api/v1/agents/{agentId}/knowledge-bases",
        "summary": "List knowledge bases bound to an agent"
    },
    "patch_agents_agentid_knowledge_bases_knowledgebaseid": {
        "name": "patch_agents_agentid_knowledge_bases_knowledgebaseid",
        "method": "PATCH",
        "path": "/api/v1/agents/{agentId}/knowledge-bases/{knowledgeBaseId}",
        "summary": "Update an agent knowledge-base binding"
    },
    "get_agents_agentid_shares": {
        "name": "get_agents_agentid_shares",
        "method": "GET",
        "path": "/api/v1/agents/{agentId}/shares",
        "summary": "List agent resource shares"
    },
    "post_agents_agentid_shares": {
        "name": "post_agents_agentid_shares",
        "method": "POST",
        "path": "/api/v1/agents/{agentId}/shares",
        "summary": "Share an agent through resource grants"
    },
    "get_agents_agentid_tools": {
        "name": "get_agents_agentid_tools",
        "method": "GET",
        "path": "/api/v1/agents/{agentId}/tools",
        "summary": "List tool bindings for an agent"
    },
    "patch_agents_agentid_tools_toolid": {
        "name": "patch_agents_agentid_tools_toolid",
        "method": "PATCH",
        "path": "/api/v1/agents/{agentId}/tools/{toolId}",
        "summary": "Update an agent tool binding"
    },
    "get_agents_agentid_versions": {
        "name": "get_agents_agentid_versions",
        "method": "GET",
        "path": "/api/v1/agents/{agentId}/versions",
        "summary": "List published agent versions"
    },
    "post_agents_agentid_versions": {
        "name": "post_agents_agentid_versions",
        "method": "POST",
        "path": "/api/v1/agents/{agentId}/versions",
        "summary": "Publish the current agent draft"
    },
    "get_agents_agentid_versions_versionid_diff": {
        "name": "get_agents_agentid_versions_versionid_diff",
        "method": "GET",
        "path": "/api/v1/agents/{agentId}/versions/{versionId}/diff",
        "summary": "Diff two published agent versions"
    },
    "post_agents_agentid_versions_versionid_rollback": {
        "name": "post_agents_agentid_versions_versionid_rollback",
        "method": "POST",
        "path": "/api/v1/agents/{agentId}/versions/{versionId}/rollback",
        "summary": "Roll an agent back to a published version"
    },
    "post_agents_agentid_voice": {
        "name": "post_agents_agentid_voice",
        "method": "POST",
        "path": "/api/v1/agents/{agentId}/voice",
        "summary": "Bind a default voice to an agent draft"
    },
    "get_api_keys": {
        "name": "get_api_keys",
        "method": "GET",
        "path": "/api/v1/api-keys",
        "summary": "List API keys"
    },
    "post_api_keys": {
        "name": "post_api_keys",
        "method": "POST",
        "path": "/api/v1/api-keys",
        "summary": "Create an API key"
    },
    "post_api_keys_bulk_revoke": {
        "name": "post_api_keys_bulk_revoke",
        "method": "POST",
        "path": "/api/v1/api-keys/bulk-revoke",
        "summary": "Revoke multiple API keys"
    },
    "post_api_keys_apikeyid_revoke": {
        "name": "post_api_keys_apikeyid_revoke",
        "method": "POST",
        "path": "/api/v1/api-keys/{apiKeyId}/revoke",
        "summary": "Revoke an API key"
    },
    "get_audit_logs": {
        "name": "get_audit_logs",
        "method": "GET",
        "path": "/api/v1/audit-logs",
        "summary": "List audit logs for the caller organization"
    },
    "get_audit_logs_csv": {
        "name": "get_audit_logs_csv",
        "method": "GET",
        "path": "/api/v1/audit-logs.csv",
        "summary": "Export filtered audit logs as CSV"
    },
    "post_auth_ldap_login": {
        "name": "post_auth_ldap_login",
        "method": "POST",
        "path": "/api/v1/auth/ldap/login",
        "summary": "Authenticate with LDAP or Active Directory bind/search"
    },
    "post_auth_local_login": {
        "name": "post_auth_local_login",
        "method": "POST",
        "path": "/api/v1/auth/local/login",
        "summary": "Authenticate with local email/password and optional local MFA code"
    },
    "post_auth_local_mfa_factors_factorid_disable": {
        "name": "post_auth_local_mfa_factors_factorid_disable",
        "method": "POST",
        "path": "/api/v1/auth/local/mfa/factors/{factorId}/disable",
        "summary": "Disable a current user local MFA factor"
    },
    "post_auth_local_mfa_recovery_codes_generate": {
        "name": "post_auth_local_mfa_recovery_codes_generate",
        "method": "POST",
        "path": "/api/v1/auth/local/mfa/recovery-codes/generate",
        "summary": "Generate one-time local MFA recovery codes"
    },
    "post_auth_local_mfa_totp_confirm": {
        "name": "post_auth_local_mfa_totp_confirm",
        "method": "POST",
        "path": "/api/v1/auth/local/mfa/totp/confirm",
        "summary": "Confirm current user TOTP MFA enrollment"
    },
    "post_auth_local_mfa_totp_enroll": {
        "name": "post_auth_local_mfa_totp_enroll",
        "method": "POST",
        "path": "/api/v1/auth/local/mfa/totp/enroll",
        "summary": "Start current user TOTP MFA enrollment"
    },
    "post_auth_local_mfa_verify": {
        "name": "post_auth_local_mfa_verify",
        "method": "POST",
        "path": "/api/v1/auth/local/mfa/verify",
        "summary": "Complete local login after MFA challenge"
    },
    "post_auth_local_password": {
        "name": "post_auth_local_password",
        "method": "POST",
        "path": "/api/v1/auth/local/password",
        "summary": "Set or change the current user local password"
    },
    "get_auth_local_status": {
        "name": "get_auth_local_status",
        "method": "GET",
        "path": "/api/v1/auth/local/status",
        "summary": "Inspect current user local password and MFA status"
    },
    "get_auth_oauth2_callback": {
        "name": "get_auth_oauth2_callback",
        "method": "GET",
        "path": "/api/v1/auth/oauth2/callback",
        "summary": "Complete browser OAuth2 login with PKCE"
    },
    "get_auth_oauth2_start": {
        "name": "get_auth_oauth2_start",
        "method": "GET",
        "path": "/api/v1/auth/oauth2/start",
        "summary": "Start browser OAuth2 login with PKCE"
    },
    "get_auth_oidc_callback": {
        "name": "get_auth_oidc_callback",
        "method": "GET",
        "path": "/api/v1/auth/oidc/callback",
        "summary": "Complete browser OIDC login with PKCE"
    },
    "get_auth_oidc_start": {
        "name": "get_auth_oidc_start",
        "method": "GET",
        "path": "/api/v1/auth/oidc/start",
        "summary": "Start browser OIDC login with PKCE"
    },
    "post_auth_saml_callback": {
        "name": "post_auth_saml_callback",
        "method": "POST",
        "path": "/api/v1/auth/saml/callback",
        "summary": "Complete browser SAML login through HTTP-POST ACS"
    },
    "get_auth_saml_metadata": {
        "name": "get_auth_saml_metadata",
        "method": "GET",
        "path": "/api/v1/auth/saml/metadata",
        "summary": "Return SAML service-provider metadata XML"
    },
    "get_auth_saml_start": {
        "name": "get_auth_saml_start",
        "method": "GET",
        "path": "/api/v1/auth/saml/start",
        "summary": "Start browser SAML login"
    },
    "get_billing_entitlements": {
        "name": "get_billing_entitlements",
        "method": "GET",
        "path": "/api/v1/billing/entitlements",
        "summary": "Get billing entitlement and quota reconciliation status"
    },
    "post_billing_entitlements_reconcile": {
        "name": "post_billing_entitlements_reconcile",
        "method": "POST",
        "path": "/api/v1/billing/entitlements/reconcile",
        "summary": "Reconcile org quotas to the current billing entitlement templates"
    },
    "post_billing_external_events": {
        "name": "post_billing_external_events",
        "method": "POST",
        "path": "/api/v1/billing/external-events",
        "summary": "Sync a sanitized external billing lifecycle event"
    },
    "get_billing_lifecycle": {
        "name": "get_billing_lifecycle",
        "method": "GET",
        "path": "/api/v1/billing/lifecycle",
        "summary": "Get billing lifecycle deadline posture"
    },
    "post_billing_lifecycle_enforce": {
        "name": "post_billing_lifecycle_enforce",
        "method": "POST",
        "path": "/api/v1/billing/lifecycle/enforce",
        "summary": "Enforce due billing lifecycle status transitions"
    },
    "get_billing_plan": {
        "name": "get_billing_plan",
        "method": "GET",
        "path": "/api/v1/billing/plan",
        "summary": "Get the current organization billing plan"
    },
    "post_billing_plan": {
        "name": "post_billing_plan",
        "method": "POST",
        "path": "/api/v1/billing/plan",
        "summary": "Apply a billing plan and org quota templates"
    },
    "post_billing_webhooks_generic": {
        "name": "post_billing_webhooks_generic",
        "method": "POST",
        "path": "/api/v1/billing/webhooks/generic",
        "summary": "Receive a signed generic billing webhook"
    },
    "post_billing_webhooks_stripe": {
        "name": "post_billing_webhooks_stripe",
        "method": "POST",
        "path": "/api/v1/billing/webhooks/stripe",
        "summary": "Receive a signed Stripe billing webhook"
    },
    "get_browser_automation_artifacts_artifactid": {
        "name": "get_browser_automation_artifacts_artifactid",
        "method": "GET",
        "path": "/api/v1/browser-automation-artifacts/{artifactId}",
        "summary": "Read a registered browser automation screenshot or trace artifact"
    },
    "post_browser_automation_tasks_claim": {
        "name": "post_browser_automation_tasks_claim",
        "method": "POST",
        "path": "/api/v1/browser-automation-tasks/claim",
        "summary": "Claim an approved browser automation workflow task"
    },
    "post_browser_automation_tasks_expire": {
        "name": "post_browser_automation_tasks_expire",
        "method": "POST",
        "path": "/api/v1/browser-automation-tasks/expire",
        "summary": "Expire stale browser automation workflow tasks"
    },
    "post_browser_automation_tasks_jobid_artifacts_uploads": {
        "name": "post_browser_automation_tasks_jobid_artifacts_uploads",
        "method": "POST",
        "path": "/api/v1/browser-automation-tasks/{jobId}/artifacts/uploads",
        "summary": "Register a screenshot or trace artifact upload for an active browser automation task"
    },
    "post_browser_automation_tasks_jobid_complete": {
        "name": "post_browser_automation_tasks_jobid_complete",
        "method": "POST",
        "path": "/api/v1/browser-automation-tasks/{jobId}/complete",
        "summary": "Complete an active browser automation task"
    },
    "post_browser_automation_tasks_jobid_fail": {
        "name": "post_browser_automation_tasks_jobid_fail",
        "method": "POST",
        "path": "/api/v1/browser-automation-tasks/{jobId}/fail",
        "summary": "Fail an active browser automation task"
    },
    "post_browser_automation_tasks_jobid_renew_lease": {
        "name": "post_browser_automation_tasks_jobid_renew_lease",
        "method": "POST",
        "path": "/api/v1/browser-automation-tasks/{jobId}/renew-lease",
        "summary": "Renew an active browser automation task lease"
    },
    "get_chat_tags": {
        "name": "get_chat_tags",
        "method": "GET",
        "path": "/api/v1/chat-tags",
        "summary": "List caller-scoped chat tags"
    },
    "get_chat_tags_tagslug_chats": {
        "name": "get_chat_tags_tagslug_chats",
        "method": "GET",
        "path": "/api/v1/chat-tags/{tagSlug}/chats",
        "summary": "List chats assigned to a caller-scoped tag"
    },
    "post_chat_completions": {
        "name": "post_chat_completions",
        "method": "POST",
        "path": "/api/v1/chat/completions",
        "summary": "Create an OpenAI-compatible chat completion"
    },
    "get_chats": {
        "name": "get_chats",
        "method": "GET",
        "path": "/api/v1/chats",
        "summary": "List chats in a workspace"
    },
    "post_chats": {
        "name": "post_chats",
        "method": "POST",
        "path": "/api/v1/chats",
        "summary": "Create a chat"
    },
    "delete_chats_chatid": {
        "name": "delete_chats_chatid",
        "method": "DELETE",
        "path": "/api/v1/chats/{chatId}",
        "summary": "Delete a chat through the governed deletion path"
    },
    "get_chats_chatid": {
        "name": "get_chats_chatid",
        "method": "GET",
        "path": "/api/v1/chats/{chatId}",
        "summary": "Get a chat"
    },
    "patch_chats_chatid": {
        "name": "patch_chats_chatid",
        "method": "PATCH",
        "path": "/api/v1/chats/{chatId}",
        "summary": "Update chat metadata"
    },
    "post_chats_chatid_archive": {
        "name": "post_chats_chatid_archive",
        "method": "POST",
        "path": "/api/v1/chats/{chatId}/archive",
        "summary": "Archive a chat"
    },
    "get_chats_chatid_comments": {
        "name": "get_chats_chatid_comments",
        "method": "GET",
        "path": "/api/v1/chats/{chatId}/comments",
        "summary": "List comments for a chat"
    },
    "post_chats_chatid_comments": {
        "name": "post_chats_chatid_comments",
        "method": "POST",
        "path": "/api/v1/chats/{chatId}/comments",
        "summary": "Create a chat comment"
    },
    "get_chats_chatid_delete_preview": {
        "name": "get_chats_chatid_delete_preview",
        "method": "GET",
        "path": "/api/v1/chats/{chatId}/delete-preview",
        "summary": "Preview chat deletion counts"
    },
    "post_chats_chatid_fork": {
        "name": "post_chats_chatid_fork",
        "method": "POST",
        "path": "/api/v1/chats/{chatId}/fork",
        "summary": "Fork a chat history into a new chat"
    },
    "post_chats_chatid_legal_hold": {
        "name": "post_chats_chatid_legal_hold",
        "method": "POST",
        "path": "/api/v1/chats/{chatId}/legal-hold",
        "summary": "Update or clear a chat legal hold"
    },
    "get_chats_chatid_message_feedback": {
        "name": "get_chats_chatid_message_feedback",
        "method": "GET",
        "path": "/api/v1/chats/{chatId}/message-feedback",
        "summary": "List the caller's assistant-message feedback for a chat"
    },
    "get_chats_chatid_messages": {
        "name": "get_chats_chatid_messages",
        "method": "GET",
        "path": "/api/v1/chats/{chatId}/messages",
        "summary": "List messages for a chat"
    },
    "get_chats_chatid_messages_messageid_attachments_attachmentid": {
        "name": "get_chats_chatid_messages_messageid_attachments_attachmentid",
        "method": "GET",
        "path": "/api/v1/chats/{chatId}/messages/{messageId}/attachments/{attachmentId}",
        "summary": "Read an authorized message image attachment"
    },
    "get_chats_chatid_messages_messageid_feedback": {
        "name": "get_chats_chatid_messages_messageid_feedback",
        "method": "GET",
        "path": "/api/v1/chats/{chatId}/messages/{messageId}/feedback",
        "summary": "Get the caller's feedback for a message"
    },
    "post_chats_chatid_messages_messageid_feedback": {
        "name": "post_chats_chatid_messages_messageid_feedback",
        "method": "POST",
        "path": "/api/v1/chats/{chatId}/messages/{messageId}/feedback",
        "summary": "Record or clear the caller's feedback for a message"
    },
    "get_chats_chatid_shares": {
        "name": "get_chats_chatid_shares",
        "method": "GET",
        "path": "/api/v1/chats/{chatId}/shares",
        "summary": "List chat resource shares"
    },
    "post_chats_chatid_shares": {
        "name": "post_chats_chatid_shares",
        "method": "POST",
        "path": "/api/v1/chats/{chatId}/shares",
        "summary": "Share a chat through resource grants"
    },
    "get_chats_chatid_tag_assignments": {
        "name": "get_chats_chatid_tag_assignments",
        "method": "GET",
        "path": "/api/v1/chats/{chatId}/tag-assignments",
        "summary": "List caller-scoped tags assigned to a chat"
    },
    "post_chats_chatid_tag_assignments": {
        "name": "post_chats_chatid_tag_assignments",
        "method": "POST",
        "path": "/api/v1/chats/{chatId}/tag-assignments",
        "summary": "Assign a caller-scoped tag to a chat"
    },
    "delete_chats_chatid_tag_assignments_tagslug": {
        "name": "delete_chats_chatid_tag_assignments_tagslug",
        "method": "DELETE",
        "path": "/api/v1/chats/{chatId}/tag-assignments/{tagSlug}",
        "summary": "Remove a caller-scoped tag assignment from a chat"
    },
    "post_chats_chatid_unarchive": {
        "name": "post_chats_chatid_unarchive",
        "method": "POST",
        "path": "/api/v1/chats/{chatId}/unarchive",
        "summary": "Restore an archived chat"
    },
    "get_collaboration_channels": {
        "name": "get_collaboration_channels",
        "method": "GET",
        "path": "/api/v1/collaboration/channels",
        "summary": "List native Romeo collaboration channels"
    },
    "post_collaboration_channels": {
        "name": "post_collaboration_channels",
        "method": "POST",
        "path": "/api/v1/collaboration/channels",
        "summary": "Create a native Romeo collaboration channel"
    },
    "post_collaboration_channels_direct_messages": {
        "name": "post_collaboration_channels_direct_messages",
        "method": "POST",
        "path": "/api/v1/collaboration/channels/direct-messages",
        "summary": "Get or create a native Romeo direct-message channel"
    },
    "delete_collaboration_channels_channelid": {
        "name": "delete_collaboration_channels_channelid",
        "method": "DELETE",
        "path": "/api/v1/collaboration/channels/{channelId}",
        "summary": "Delete a native Romeo collaboration channel"
    },
    "get_collaboration_channels_channelid": {
        "name": "get_collaboration_channels_channelid",
        "method": "GET",
        "path": "/api/v1/collaboration/channels/{channelId}",
        "summary": "Get a native Romeo collaboration channel"
    },
    "patch_collaboration_channels_channelid": {
        "name": "patch_collaboration_channels_channelid",
        "method": "PATCH",
        "path": "/api/v1/collaboration/channels/{channelId}",
        "summary": "Update a native Romeo collaboration channel"
    },
    "get_collaboration_channels_channelid_events": {
        "name": "get_collaboration_channels_channelid_events",
        "method": "GET",
        "path": "/api/v1/collaboration/channels/{channelId}/events",
        "summary": "Stream native Romeo channel events"
    },
    "get_collaboration_channels_channelid_members": {
        "name": "get_collaboration_channels_channelid_members",
        "method": "GET",
        "path": "/api/v1/collaboration/channels/{channelId}/members",
        "summary": "List native Romeo channel members"
    },
    "post_collaboration_channels_channelid_members": {
        "name": "post_collaboration_channels_channelid_members",
        "method": "POST",
        "path": "/api/v1/collaboration/channels/{channelId}/members",
        "summary": "Add native Romeo channel members"
    },
    "delete_collaboration_channels_channelid_members_userid": {
        "name": "delete_collaboration_channels_channelid_members_userid",
        "method": "DELETE",
        "path": "/api/v1/collaboration/channels/{channelId}/members/{userId}",
        "summary": "Remove a native Romeo channel member"
    },
    "get_collaboration_channels_channelid_messages": {
        "name": "get_collaboration_channels_channelid_messages",
        "method": "GET",
        "path": "/api/v1/collaboration/channels/{channelId}/messages",
        "summary": "List native Romeo channel messages"
    },
    "post_collaboration_channels_channelid_messages": {
        "name": "post_collaboration_channels_channelid_messages",
        "method": "POST",
        "path": "/api/v1/collaboration/channels/{channelId}/messages",
        "summary": "Post a native Romeo channel message"
    },
    "get_collaboration_channels_channelid_messages_pinned": {
        "name": "get_collaboration_channels_channelid_messages_pinned",
        "method": "GET",
        "path": "/api/v1/collaboration/channels/{channelId}/messages/pinned",
        "summary": "List pinned native Romeo channel messages"
    },
    "delete_collaboration_channels_channelid_messages_messageid": {
        "name": "delete_collaboration_channels_channelid_messages_messageid",
        "method": "DELETE",
        "path": "/api/v1/collaboration/channels/{channelId}/messages/{messageId}",
        "summary": "Delete a native Romeo channel message"
    },
    "get_collaboration_channels_channelid_messages_messageid": {
        "name": "get_collaboration_channels_channelid_messages_messageid",
        "method": "GET",
        "path": "/api/v1/collaboration/channels/{channelId}/messages/{messageId}",
        "summary": "Get a native Romeo channel message"
    },
    "patch_collaboration_channels_channelid_messages_messageid": {
        "name": "patch_collaboration_channels_channelid_messages_messageid",
        "method": "PATCH",
        "path": "/api/v1/collaboration/channels/{channelId}/messages/{messageId}",
        "summary": "Update a native Romeo channel message"
    },
    "post_collaboration_channels_channelid_messages_messageid_pin": {
        "name": "post_collaboration_channels_channelid_messages_messageid_pin",
        "method": "POST",
        "path": "/api/v1/collaboration/channels/{channelId}/messages/{messageId}/pin",
        "summary": "Pin or unpin a native Romeo channel message"
    },
    "post_collaboration_channels_channelid_messages_messageid_reactions": {
        "name": "post_collaboration_channels_channelid_messages_messageid_reactions",
        "method": "POST",
        "path": "/api/v1/collaboration/channels/{channelId}/messages/{messageId}/reactions",
        "summary": "Add a native Romeo channel message reaction"
    },
    "delete_collaboration_channels_channelid_messages_messageid_reactions_name": {
        "name": "delete_collaboration_channels_channelid_messages_messageid_reactions_name",
        "method": "DELETE",
        "path": "/api/v1/collaboration/channels/{channelId}/messages/{messageId}/reactions/{name}",
        "summary": "Remove a native Romeo channel message reaction"
    },
    "get_collaboration_channels_channelid_messages_messageid_thread": {
        "name": "get_collaboration_channels_channelid_messages_messageid_thread",
        "method": "GET",
        "path": "/api/v1/collaboration/channels/{channelId}/messages/{messageId}/thread",
        "summary": "List native Romeo channel message thread replies"
    },
    "post_collaboration_channels_channelid_read": {
        "name": "post_collaboration_channels_channelid_read",
        "method": "POST",
        "path": "/api/v1/collaboration/channels/{channelId}/read",
        "summary": "Mark a native Romeo channel as read"
    },
    "get_data_connectors": {
        "name": "get_data_connectors",
        "method": "GET",
        "path": "/api/v1/data-connectors",
        "summary": "List data connectors for a workspace"
    },
    "post_data_connectors": {
        "name": "post_data_connectors",
        "method": "POST",
        "path": "/api/v1/data-connectors",
        "summary": "Create a data connector for a knowledge base"
    },
    "get_data_connectors_catalog": {
        "name": "get_data_connectors_catalog",
        "method": "GET",
        "path": "/api/v1/data-connectors/catalog",
        "summary": "Inspect supported data connector types and runtime posture"
    },
    "post_data_connectors_connectorid_sync": {
        "name": "post_data_connectors_connectorid_sync",
        "method": "POST",
        "path": "/api/v1/data-connectors/{connectorId}/sync",
        "summary": "Start a data connector sync"
    },
    "get_data_connectors_connectorid_syncs": {
        "name": "get_data_connectors_connectorid_syncs",
        "method": "GET",
        "path": "/api/v1/data-connectors/{connectorId}/syncs",
        "summary": "List data connector sync attempts"
    },
    "get_delegated_oauth_callback": {
        "name": "get_delegated_oauth_callback",
        "method": "GET",
        "path": "/api/v1/delegated-oauth/callback",
        "summary": "Receive delegated OAuth provider callback"
    },
    "get_delegated_oauth_connections": {
        "name": "get_delegated_oauth_connections",
        "method": "GET",
        "path": "/api/v1/delegated-oauth/connections",
        "summary": "List delegated OAuth connector account links"
    },
    "post_delegated_oauth_connections_connectionid_revoke": {
        "name": "post_delegated_oauth_connections_connectionid_revoke",
        "method": "POST",
        "path": "/api/v1/delegated-oauth/connections/{connectionId}/revoke",
        "summary": "Revoke a delegated OAuth connector account link"
    },
    "get_delegated_oauth_providers": {
        "name": "get_delegated_oauth_providers",
        "method": "GET",
        "path": "/api/v1/delegated-oauth/providers",
        "summary": "List delegated OAuth providers available for connectors"
    },
    "post_delegated_oauth_start": {
        "name": "post_delegated_oauth_start",
        "method": "POST",
        "path": "/api/v1/delegated-oauth/start",
        "summary": "Start a delegated OAuth connector authorization flow"
    },
    "get_device_authorizations": {
        "name": "get_device_authorizations",
        "method": "GET",
        "path": "/api/v1/device-authorizations",
        "summary": "List device authorizations for the current user"
    },
    "post_device_authorizations": {
        "name": "post_device_authorizations",
        "method": "POST",
        "path": "/api/v1/device-authorizations",
        "summary": "Create a refreshable device authorization"
    },
    "post_device_authorizations_refresh": {
        "name": "post_device_authorizations_refresh",
        "method": "POST",
        "path": "/api/v1/device-authorizations/refresh",
        "summary": "Rotate a device authorization with a refresh token"
    },
    "post_device_authorizations_deviceauthorizationid_revoke": {
        "name": "post_device_authorizations_deviceauthorizationid_revoke",
        "method": "POST",
        "path": "/api/v1/device-authorizations/{deviceAuthorizationId}/revoke",
        "summary": "Revoke a device authorization"
    },
    "get_docs": {
        "name": "get_docs",
        "method": "GET",
        "path": "/api/v1/docs",
        "summary": "Render local OpenAPI documentation"
    },
    "post_embeddings": {
        "name": "post_embeddings",
        "method": "POST",
        "path": "/api/v1/embeddings",
        "summary": "Create OpenAI-compatible embeddings"
    },
    "post_eval_run_results_resultid_rating": {
        "name": "post_eval_run_results_resultid_rating",
        "method": "POST",
        "path": "/api/v1/eval-run-results/{resultId}/rating",
        "summary": "Rate an eval run result"
    },
    "get_eval_runs_runid_ratings": {
        "name": "get_eval_runs_runid_ratings",
        "method": "GET",
        "path": "/api/v1/eval-runs/{runId}/ratings",
        "summary": "List human ratings for an eval run"
    },
    "get_eval_runs_runid_results": {
        "name": "get_eval_runs_runid_results",
        "method": "GET",
        "path": "/api/v1/eval-runs/{runId}/results",
        "summary": "List eval run results"
    },
    "post_eval_suites": {
        "name": "post_eval_suites",
        "method": "POST",
        "path": "/api/v1/eval-suites",
        "summary": "Create an eval suite"
    },
    "post_eval_suites_suiteid_model_comparisons": {
        "name": "post_eval_suites_suiteid_model_comparisons",
        "method": "POST",
        "path": "/api/v1/eval-suites/{suiteId}/model-comparisons",
        "summary": "Run an eval suite across multiple models"
    },
    "post_eval_suites_suiteid_runs": {
        "name": "post_eval_suites_suiteid_runs",
        "method": "POST",
        "path": "/api/v1/eval-suites/{suiteId}/runs",
        "summary": "Run an eval suite against an agent draft"
    },
    "get_favorites": {
        "name": "get_favorites",
        "method": "GET",
        "path": "/api/v1/favorites",
        "summary": "List caller resource favorites"
    },
    "post_favorites": {
        "name": "post_favorites",
        "method": "POST",
        "path": "/api/v1/favorites",
        "summary": "Favorite an agent or knowledge base"
    },
    "delete_favorites_favoriteid": {
        "name": "delete_favorites_favoriteid",
        "method": "DELETE",
        "path": "/api/v1/favorites/{favoriteId}",
        "summary": "Delete a resource favorite"
    },
    "get_files": {
        "name": "get_files",
        "method": "GET",
        "path": "/api/v1/files",
        "summary": "List authorized files"
    },
    "post_files": {
        "name": "post_files",
        "method": "POST",
        "path": "/api/v1/files",
        "summary": "Upload a bounded file"
    },
    "post_files_uploads": {
        "name": "post_files_uploads",
        "method": "POST",
        "path": "/api/v1/files/uploads",
        "summary": "Create a direct file upload session"
    },
    "post_files_uploads_resumable": {
        "name": "post_files_uploads_resumable",
        "method": "POST",
        "path": "/api/v1/files/uploads/resumable",
        "summary": "Create a resumable file upload session"
    },
    "delete_files_uploads_resumable_fileid": {
        "name": "delete_files_uploads_resumable_fileid",
        "method": "DELETE",
        "path": "/api/v1/files/uploads/resumable/{fileId}",
        "summary": "Cancel a resumable file upload session"
    },
    "get_files_uploads_resumable_fileid": {
        "name": "get_files_uploads_resumable_fileid",
        "method": "GET",
        "path": "/api/v1/files/uploads/resumable/{fileId}",
        "summary": "Refresh a resumable file upload session"
    },
    "post_files_uploads_resumable_fileid_complete": {
        "name": "post_files_uploads_resumable_fileid_complete",
        "method": "POST",
        "path": "/api/v1/files/uploads/resumable/{fileId}/complete",
        "summary": "Complete a resumable file upload session"
    },
    "delete_files_uploads_fileid": {
        "name": "delete_files_uploads_fileid",
        "method": "DELETE",
        "path": "/api/v1/files/uploads/{fileId}",
        "summary": "Cancel a direct file upload session"
    },
    "get_files_uploads_fileid": {
        "name": "get_files_uploads_fileid",
        "method": "GET",
        "path": "/api/v1/files/uploads/{fileId}",
        "summary": "Refresh a direct file upload session"
    },
    "post_files_uploads_fileid_complete": {
        "name": "post_files_uploads_fileid_complete",
        "method": "POST",
        "path": "/api/v1/files/uploads/{fileId}/complete",
        "summary": "Complete a direct file upload session"
    },
    "delete_files_fileid": {
        "name": "delete_files_fileid",
        "method": "DELETE",
        "path": "/api/v1/files/{fileId}",
        "summary": "Delete an authorized file"
    },
    "get_files_fileid": {
        "name": "get_files_fileid",
        "method": "GET",
        "path": "/api/v1/files/{fileId}",
        "summary": "Get authorized file metadata"
    },
    "get_files_fileid_content": {
        "name": "get_files_fileid_content",
        "method": "GET",
        "path": "/api/v1/files/{fileId}/content",
        "summary": "Read authorized file bytes"
    },
    "get_files_fileid_shares": {
        "name": "get_files_fileid_shares",
        "method": "GET",
        "path": "/api/v1/files/{fileId}/shares",
        "summary": "List file resource shares"
    },
    "post_files_fileid_shares": {
        "name": "post_files_fileid_shares",
        "method": "POST",
        "path": "/api/v1/files/{fileId}/shares",
        "summary": "Share a file through resource grants"
    },
    "get_folders": {
        "name": "get_folders",
        "method": "GET",
        "path": "/api/v1/folders",
        "summary": "List caller-visible workspace folders"
    },
    "post_folders": {
        "name": "post_folders",
        "method": "POST",
        "path": "/api/v1/folders",
        "summary": "Create a workspace folder"
    },
    "delete_folders_folderid": {
        "name": "delete_folders_folderid",
        "method": "DELETE",
        "path": "/api/v1/folders/{folderId}",
        "summary": "Delete a workspace folder"
    },
    "get_folders_folderid": {
        "name": "get_folders_folderid",
        "method": "GET",
        "path": "/api/v1/folders/{folderId}",
        "summary": "Get a workspace folder"
    },
    "patch_folders_folderid": {
        "name": "patch_folders_folderid",
        "method": "PATCH",
        "path": "/api/v1/folders/{folderId}",
        "summary": "Update a workspace folder"
    },
    "get_folders_folderid_items": {
        "name": "get_folders_folderid_items",
        "method": "GET",
        "path": "/api/v1/folders/{folderId}/items",
        "summary": "List visible items in a workspace folder"
    },
    "post_folders_folderid_items": {
        "name": "post_folders_folderid_items",
        "method": "POST",
        "path": "/api/v1/folders/{folderId}/items",
        "summary": "Add an accessible resource to a workspace folder"
    },
    "delete_folders_folderid_items_itemid": {
        "name": "delete_folders_folderid_items_itemid",
        "method": "DELETE",
        "path": "/api/v1/folders/{folderId}/items/{itemId}",
        "summary": "Remove an item from a workspace folder"
    },
    "get_folders_folderid_shares": {
        "name": "get_folders_folderid_shares",
        "method": "GET",
        "path": "/api/v1/folders/{folderId}/shares",
        "summary": "List folder resource shares"
    },
    "post_folders_folderid_shares": {
        "name": "post_folders_folderid_shares",
        "method": "POST",
        "path": "/api/v1/folders/{folderId}/shares",
        "summary": "Share a folder through resource grants"
    },
    "get_governance_compliance_report": {
        "name": "get_governance_compliance_report",
        "method": "GET",
        "path": "/api/v1/governance/compliance-report",
        "summary": "Export a sanitized governance compliance report"
    },
    "get_governance_compliance_report_csv": {
        "name": "get_governance_compliance_report_csv",
        "method": "GET",
        "path": "/api/v1/governance/compliance-report.csv",
        "summary": "Export a sanitized governance compliance report as CSV"
    },
    "post_governance_data_deletions_execute": {
        "name": "post_governance_data_deletions_execute",
        "method": "POST",
        "path": "/api/v1/governance/data-deletions/execute",
        "summary": "Execute a governed data deletion workflow"
    },
    "post_governance_data_deletions_preview": {
        "name": "post_governance_data_deletions_preview",
        "method": "POST",
        "path": "/api/v1/governance/data-deletions/preview",
        "summary": "Preview a governed data deletion workflow"
    },
    "post_governance_data_exports_execute": {
        "name": "post_governance_data_exports_execute",
        "method": "POST",
        "path": "/api/v1/governance/data-exports/execute",
        "summary": "Execute a governed customer data export"
    },
    "get_governance_data_exports_packages": {
        "name": "get_governance_data_exports_packages",
        "method": "GET",
        "path": "/api/v1/governance/data-exports/packages",
        "summary": "List governed customer data export packages"
    },
    "post_governance_data_exports_packages": {
        "name": "post_governance_data_exports_packages",
        "method": "POST",
        "path": "/api/v1/governance/data-exports/packages",
        "summary": "Create an object-store package for a governed customer data export"
    },
    "delete_governance_data_exports_packages_packageid": {
        "name": "delete_governance_data_exports_packages_packageid",
        "method": "DELETE",
        "path": "/api/v1/governance/data-exports/packages/{packageId}",
        "summary": "Delete a governed customer data export package"
    },
    "get_governance_data_exports_packages_packageid_content": {
        "name": "get_governance_data_exports_packages_packageid_content",
        "method": "GET",
        "path": "/api/v1/governance/data-exports/packages/{packageId}/content",
        "summary": "Download a governed customer data export package"
    },
    "post_governance_data_exports_preview": {
        "name": "post_governance_data_exports_preview",
        "method": "POST",
        "path": "/api/v1/governance/data-exports/preview",
        "summary": "Preview a governed customer data export"
    },
    "get_governance_data_rights_coverage": {
        "name": "get_governance_data_rights_coverage",
        "method": "GET",
        "path": "/api/v1/governance/data-rights/coverage",
        "summary": "Get metadata-only data rights deletion, export, retention, and support coverage"
    },
    "get_governance_identity_lifecycle_policy": {
        "name": "get_governance_identity_lifecycle_policy",
        "method": "GET",
        "path": "/api/v1/governance/identity-lifecycle-policy",
        "summary": "Get the enterprise identity lifecycle policy posture"
    },
    "get_governance_retention": {
        "name": "get_governance_retention",
        "method": "GET",
        "path": "/api/v1/governance/retention",
        "summary": "Get governance retention policy"
    },
    "patch_governance_retention": {
        "name": "patch_governance_retention",
        "method": "PATCH",
        "path": "/api/v1/governance/retention",
        "summary": "Update governance retention policy"
    },
    "post_governance_retention_enforce": {
        "name": "post_governance_retention_enforce",
        "method": "POST",
        "path": "/api/v1/governance/retention/enforce",
        "summary": "Enforce audit-log and browser automation artifact retention for the current organization"
    },
    "get_groups": {
        "name": "get_groups",
        "method": "GET",
        "path": "/api/v1/groups",
        "summary": "List organization groups"
    },
    "post_groups": {
        "name": "post_groups",
        "method": "POST",
        "path": "/api/v1/groups",
        "summary": "Create an organization group"
    },
    "get_groups_groupid_members": {
        "name": "get_groups_groupid_members",
        "method": "GET",
        "path": "/api/v1/groups/{groupId}/members",
        "summary": "List group memberships"
    },
    "post_groups_groupid_members": {
        "name": "post_groups_groupid_members",
        "method": "POST",
        "path": "/api/v1/groups/{groupId}/members",
        "summary": "Add a user to a group"
    },
    "delete_groups_groupid_members_userid": {
        "name": "delete_groups_groupid_members_userid",
        "method": "DELETE",
        "path": "/api/v1/groups/{groupId}/members/{userId}",
        "summary": "Remove a user from a group"
    },
    "get_health": {
        "name": "get_health",
        "method": "GET",
        "path": "/api/v1/health",
        "summary": "Check API readiness"
    },
    "get_jobs": {
        "name": "get_jobs",
        "method": "GET",
        "path": "/api/v1/jobs",
        "summary": "List background jobs"
    },
    "get_jobs_operational_summary": {
        "name": "get_jobs_operational_summary",
        "method": "GET",
        "path": "/api/v1/jobs/operational-summary",
        "summary": "Summarize background job lag and alert state"
    },
    "get_knowledge_bases": {
        "name": "get_knowledge_bases",
        "method": "GET",
        "path": "/api/v1/knowledge-bases",
        "summary": "List knowledge bases in a workspace"
    },
    "post_knowledge_bases": {
        "name": "post_knowledge_bases",
        "method": "POST",
        "path": "/api/v1/knowledge-bases",
        "summary": "Create a knowledge base"
    },
    "post_knowledge_bases_query": {
        "name": "post_knowledge_bases_query",
        "method": "POST",
        "path": "/api/v1/knowledge-bases/query",
        "summary": "Query authorized knowledge bases with a tiered retrieval plan"
    },
    "get_knowledge_bases_knowledgebaseid": {
        "name": "get_knowledge_bases_knowledgebaseid",
        "method": "GET",
        "path": "/api/v1/knowledge-bases/{knowledgeBaseId}",
        "summary": "Get a knowledge base"
    },
    "patch_knowledge_bases_knowledgebaseid": {
        "name": "patch_knowledge_bases_knowledgebaseid",
        "method": "PATCH",
        "path": "/api/v1/knowledge-bases/{knowledgeBaseId}",
        "summary": "Update a knowledge base"
    },
    "post_knowledge_bases_knowledgebaseid_embeddings": {
        "name": "post_knowledge_bases_knowledgebaseid_embeddings",
        "method": "POST",
        "path": "/api/v1/knowledge-bases/{knowledgeBaseId}/embeddings",
        "summary": "Index provider embeddings for knowledge chunks"
    },
    "post_knowledge_bases_knowledgebaseid_query": {
        "name": "post_knowledge_bases_knowledgebaseid_query",
        "method": "POST",
        "path": "/api/v1/knowledge-bases/{knowledgeBaseId}/query",
        "summary": "Query a knowledge base"
    },
    "get_knowledge_bases_knowledgebaseid_shares": {
        "name": "get_knowledge_bases_knowledgebaseid_shares",
        "method": "GET",
        "path": "/api/v1/knowledge-bases/{knowledgeBaseId}/shares",
        "summary": "List knowledge-base resource shares"
    },
    "post_knowledge_bases_knowledgebaseid_shares": {
        "name": "post_knowledge_bases_knowledgebaseid_shares",
        "method": "POST",
        "path": "/api/v1/knowledge-bases/{knowledgeBaseId}/shares",
        "summary": "Share a knowledge base through resource grants"
    },
    "get_knowledge_bases_knowledgebaseid_sources": {
        "name": "get_knowledge_bases_knowledgebaseid_sources",
        "method": "GET",
        "path": "/api/v1/knowledge-bases/{knowledgeBaseId}/sources",
        "summary": "List knowledge sources"
    },
    "post_knowledge_bases_knowledgebaseid_sources": {
        "name": "post_knowledge_bases_knowledgebaseid_sources",
        "method": "POST",
        "path": "/api/v1/knowledge-bases/{knowledgeBaseId}/sources",
        "summary": "Register a knowledge source upload"
    },
    "delete_knowledge_bases_knowledgebaseid_sources_sourceid": {
        "name": "delete_knowledge_bases_knowledgebaseid_sources_sourceid",
        "method": "DELETE",
        "path": "/api/v1/knowledge-bases/{knowledgeBaseId}/sources/{sourceId}",
        "summary": "Delete a knowledge source"
    },
    "post_knowledge_bases_knowledgebaseid_sources_sourceid_complete": {
        "name": "post_knowledge_bases_knowledgebaseid_sources_sourceid_complete",
        "method": "POST",
        "path": "/api/v1/knowledge-bases/{knowledgeBaseId}/sources/{sourceId}/complete",
        "summary": "Complete a direct knowledge upload and index text content"
    },
    "post_knowledge_bases_knowledgebaseid_sources_sourceid_extract": {
        "name": "post_knowledge_bases_knowledgebaseid_sources_sourceid_extract",
        "method": "POST",
        "path": "/api/v1/knowledge-bases/{knowledgeBaseId}/sources/{sourceId}/extract",
        "summary": "Run a deferred knowledge extraction job"
    },
    "post_knowledge_bases_knowledgebaseid_sources_sourceid_reindex": {
        "name": "post_knowledge_bases_knowledgebaseid_sources_sourceid_reindex",
        "method": "POST",
        "path": "/api/v1/knowledge-bases/{knowledgeBaseId}/sources/{sourceId}/reindex",
        "summary": "Reindex a knowledge source"
    },
    "post_knowledge_bases_knowledgebaseid_uploads": {
        "name": "post_knowledge_bases_knowledgebaseid_uploads",
        "method": "POST",
        "path": "/api/v1/knowledge-bases/{knowledgeBaseId}/uploads",
        "summary": "Create a presigned knowledge source upload"
    },
    "get_me": {
        "name": "get_me",
        "method": "GET",
        "path": "/api/v1/me",
        "summary": "Get current subject and bootstrap context"
    },
    "patch_me": {
        "name": "patch_me",
        "method": "PATCH",
        "path": "/api/v1/me",
        "summary": "Update the current user's email or display name"
    },
    "post_messages_messageid_speech": {
        "name": "post_messages_messageid_speech",
        "method": "POST",
        "path": "/api/v1/messages/{messageId}/speech",
        "summary": "Generate speech for an assistant message"
    },
    "get_models": {
        "name": "get_models",
        "method": "GET",
        "path": "/api/v1/models",
        "summary": "List base models visible to the caller"
    },
    "patch_models_modelid_pricing": {
        "name": "patch_models_modelid_pricing",
        "method": "PATCH",
        "path": "/api/v1/models/{modelId}/pricing",
        "summary": "Update base model token pricing"
    },
    "get_notification_channels": {
        "name": "get_notification_channels",
        "method": "GET",
        "path": "/api/v1/notification-channels",
        "summary": "List current user notification delivery channels"
    },
    "post_notification_channels": {
        "name": "post_notification_channels",
        "method": "POST",
        "path": "/api/v1/notification-channels",
        "summary": "Create a current user notification delivery channel"
    },
    "get_notification_deliveries": {
        "name": "get_notification_deliveries",
        "method": "GET",
        "path": "/api/v1/notification-deliveries",
        "summary": "List current user notification delivery ledger records"
    },
    "post_notification_deliveries_retry_due": {
        "name": "post_notification_deliveries_retry_due",
        "method": "POST",
        "path": "/api/v1/notification-deliveries/retry-due",
        "summary": "Retry due failed notification deliveries"
    },
    "get_notifications": {
        "name": "get_notifications",
        "method": "GET",
        "path": "/api/v1/notifications",
        "summary": "List current user notifications"
    },
    "post_notifications_notificationid_read": {
        "name": "post_notifications_notificationid_read",
        "method": "POST",
        "path": "/api/v1/notifications/{notificationId}/read",
        "summary": "Mark a user notification read"
    },
    "get_openai_models": {
        "name": "get_openai_models",
        "method": "GET",
        "path": "/api/v1/openai/models",
        "summary": "List OpenAI-compatible models"
    },
    "get_openai_models_model": {
        "name": "get_openai_models_model",
        "method": "GET",
        "path": "/api/v1/openai/models/{model}",
        "summary": "Retrieve an OpenAI-compatible model"
    },
    "get_organizations": {
        "name": "get_organizations",
        "method": "GET",
        "path": "/api/v1/organizations",
        "summary": "List organizations visible to the caller"
    },
    "get_prompt_marketplace": {
        "name": "get_prompt_marketplace",
        "method": "GET",
        "path": "/api/v1/prompt-marketplace",
        "summary": "List visible marketplace prompt templates"
    },
    "get_prompt_templates": {
        "name": "get_prompt_templates",
        "method": "GET",
        "path": "/api/v1/prompt-templates",
        "summary": "List visible prompt templates"
    },
    "post_prompt_templates": {
        "name": "post_prompt_templates",
        "method": "POST",
        "path": "/api/v1/prompt-templates",
        "summary": "Create a prompt template"
    },
    "delete_prompt_templates_prompttemplateid": {
        "name": "delete_prompt_templates_prompttemplateid",
        "method": "DELETE",
        "path": "/api/v1/prompt-templates/{promptTemplateId}",
        "summary": "Delete a prompt template"
    },
    "get_prompt_templates_prompttemplateid": {
        "name": "get_prompt_templates_prompttemplateid",
        "method": "GET",
        "path": "/api/v1/prompt-templates/{promptTemplateId}",
        "summary": "Get a prompt template"
    },
    "patch_prompt_templates_prompttemplateid": {
        "name": "patch_prompt_templates_prompttemplateid",
        "method": "PATCH",
        "path": "/api/v1/prompt-templates/{promptTemplateId}",
        "summary": "Update a prompt template"
    },
    "get_prompt_templates_prompttemplateid_shares": {
        "name": "get_prompt_templates_prompttemplateid_shares",
        "method": "GET",
        "path": "/api/v1/prompt-templates/{promptTemplateId}/shares",
        "summary": "List prompt-template resource shares"
    },
    "post_prompt_templates_prompttemplateid_shares": {
        "name": "post_prompt_templates_prompttemplateid_shares",
        "method": "POST",
        "path": "/api/v1/prompt-templates/{promptTemplateId}/shares",
        "summary": "Share a prompt template through resource grants"
    },
    "get_providers": {
        "name": "get_providers",
        "method": "GET",
        "path": "/api/v1/providers",
        "summary": "List configured model providers"
    },
    "post_providers": {
        "name": "post_providers",
        "method": "POST",
        "path": "/api/v1/providers",
        "summary": "Create a provider instance"
    },
    "get_providers_operational_summary": {
        "name": "get_providers_operational_summary",
        "method": "GET",
        "path": "/api/v1/providers/operational-summary",
        "summary": "Summarize model-provider health and resilience state"
    },
    "post_providers_providerid_sync": {
        "name": "post_providers_providerid_sync",
        "method": "POST",
        "path": "/api/v1/providers/{providerId}/sync",
        "summary": "Sync provider models"
    },
    "get_quotas": {
        "name": "get_quotas",
        "method": "GET",
        "path": "/api/v1/quotas",
        "summary": "List quota buckets"
    },
    "post_quotas": {
        "name": "post_quotas",
        "method": "POST",
        "path": "/api/v1/quotas",
        "summary": "Create a quota bucket"
    },
    "get_quotas_distributed_status": {
        "name": "get_quotas_distributed_status",
        "method": "GET",
        "path": "/api/v1/quotas/distributed-status",
        "summary": "Get distributed quota coordination status"
    },
    "delete_quotas_quotabucketid": {
        "name": "delete_quotas_quotabucketid",
        "method": "DELETE",
        "path": "/api/v1/quotas/{quotaBucketId}",
        "summary": "Delete a quota bucket"
    },
    "patch_quotas_quotabucketid": {
        "name": "patch_quotas_quotabucketid",
        "method": "PATCH",
        "path": "/api/v1/quotas/{quotaBucketId}",
        "summary": "Update a quota bucket"
    },
    "post_runs": {
        "name": "post_runs",
        "method": "POST",
        "path": "/api/v1/runs",
        "summary": "Start a streamed chat run"
    },
    "get_runs_runid": {
        "name": "get_runs_runid",
        "method": "GET",
        "path": "/api/v1/runs/{runId}",
        "summary": "Get run state"
    },
    "post_runs_runid_cancel": {
        "name": "post_runs_runid_cancel",
        "method": "POST",
        "path": "/api/v1/runs/{runId}/cancel",
        "summary": "Cancel an active run"
    },
    "get_runs_runid_events": {
        "name": "get_runs_runid_events",
        "method": "GET",
        "path": "/api/v1/runs/{runId}/events",
        "summary": "Stream or replay run events"
    },
    "post_runs_runid_tools_toolid_execute": {
        "name": "post_runs_runid_tools_toolid_execute",
        "method": "POST",
        "path": "/api/v1/runs/{runId}/tools/{toolId}/execute",
        "summary": "Execute a model-requested tool call for a run"
    },
    "get_scim_v2_groups": {
        "name": "get_scim_v2_groups",
        "method": "GET",
        "path": "/api/v1/scim/v2/Groups",
        "summary": "List SCIM groups"
    },
    "post_scim_v2_groups": {
        "name": "post_scim_v2_groups",
        "method": "POST",
        "path": "/api/v1/scim/v2/Groups",
        "summary": "Create a SCIM group"
    },
    "delete_scim_v2_groups_groupid": {
        "name": "delete_scim_v2_groups_groupid",
        "method": "DELETE",
        "path": "/api/v1/scim/v2/Groups/{groupId}",
        "summary": "Delete a SCIM group and revoke group grants"
    },
    "get_scim_v2_groups_groupid": {
        "name": "get_scim_v2_groups_groupid",
        "method": "GET",
        "path": "/api/v1/scim/v2/Groups/{groupId}",
        "summary": "Get a SCIM group"
    },
    "patch_scim_v2_groups_groupid": {
        "name": "patch_scim_v2_groups_groupid",
        "method": "PATCH",
        "path": "/api/v1/scim/v2/Groups/{groupId}",
        "summary": "Patch a SCIM group"
    },
    "put_scim_v2_groups_groupid": {
        "name": "put_scim_v2_groups_groupid",
        "method": "PUT",
        "path": "/api/v1/scim/v2/Groups/{groupId}",
        "summary": "Replace a SCIM group"
    },
    "get_scim_v2_resourcetypes": {
        "name": "get_scim_v2_resourcetypes",
        "method": "GET",
        "path": "/api/v1/scim/v2/ResourceTypes",
        "summary": "List SCIM resource types"
    },
    "get_scim_v2_schemas": {
        "name": "get_scim_v2_schemas",
        "method": "GET",
        "path": "/api/v1/scim/v2/Schemas",
        "summary": "List SCIM schemas"
    },
    "get_scim_v2_serviceproviderconfig": {
        "name": "get_scim_v2_serviceproviderconfig",
        "method": "GET",
        "path": "/api/v1/scim/v2/ServiceProviderConfig",
        "summary": "Get SCIM service provider configuration"
    },
    "get_scim_v2_users": {
        "name": "get_scim_v2_users",
        "method": "GET",
        "path": "/api/v1/scim/v2/Users",
        "summary": "List SCIM users"
    },
    "post_scim_v2_users": {
        "name": "post_scim_v2_users",
        "method": "POST",
        "path": "/api/v1/scim/v2/Users",
        "summary": "Create a SCIM user"
    },
    "delete_scim_v2_users_userid": {
        "name": "delete_scim_v2_users_userid",
        "method": "DELETE",
        "path": "/api/v1/scim/v2/Users/{userId}",
        "summary": "Deactivate a SCIM user"
    },
    "get_scim_v2_users_userid": {
        "name": "get_scim_v2_users_userid",
        "method": "GET",
        "path": "/api/v1/scim/v2/Users/{userId}",
        "summary": "Get a SCIM user"
    },
    "patch_scim_v2_users_userid": {
        "name": "patch_scim_v2_users_userid",
        "method": "PATCH",
        "path": "/api/v1/scim/v2/Users/{userId}",
        "summary": "Patch a SCIM user"
    },
    "put_scim_v2_users_userid": {
        "name": "put_scim_v2_users_userid",
        "method": "PUT",
        "path": "/api/v1/scim/v2/Users/{userId}",
        "summary": "Replace a SCIM user"
    },
    "get_service_accounts": {
        "name": "get_service_accounts",
        "method": "GET",
        "path": "/api/v1/service-accounts",
        "summary": "List service accounts"
    },
    "post_service_accounts": {
        "name": "post_service_accounts",
        "method": "POST",
        "path": "/api/v1/service-accounts",
        "summary": "Create a service account"
    },
    "post_service_accounts_bulk_disable": {
        "name": "post_service_accounts_bulk_disable",
        "method": "POST",
        "path": "/api/v1/service-accounts/bulk-disable",
        "summary": "Disable multiple service accounts and invalidate their API keys"
    },
    "post_service_accounts_serviceaccountid_api_keys": {
        "name": "post_service_accounts_serviceaccountid_api_keys",
        "method": "POST",
        "path": "/api/v1/service-accounts/{serviceAccountId}/api-keys",
        "summary": "Create a scoped API key for a service account"
    },
    "post_service_accounts_serviceaccountid_disable": {
        "name": "post_service_accounts_serviceaccountid_disable",
        "method": "POST",
        "path": "/api/v1/service-accounts/{serviceAccountId}/disable",
        "summary": "Disable a service account and invalidate its API keys"
    },
    "get_sessions": {
        "name": "get_sessions",
        "method": "GET",
        "path": "/api/v1/sessions",
        "summary": "List local sessions for the current user"
    },
    "post_sessions": {
        "name": "post_sessions",
        "method": "POST",
        "path": "/api/v1/sessions",
        "summary": "Create an HttpOnly local session for the current user"
    },
    "delete_sessions_current": {
        "name": "delete_sessions_current",
        "method": "DELETE",
        "path": "/api/v1/sessions/current",
        "summary": "Revoke the current local session"
    },
    "post_sessions_revoke_others": {
        "name": "post_sessions_revoke_others",
        "method": "POST",
        "path": "/api/v1/sessions/revoke-others",
        "summary": "Revoke all other active local sessions for the current user"
    },
    "delete_sessions_sessionid": {
        "name": "delete_sessions_sessionid",
        "method": "DELETE",
        "path": "/api/v1/sessions/{sessionId}",
        "summary": "Revoke a local session by ID"
    },
    "get_share_targets": {
        "name": "get_share_targets",
        "method": "GET",
        "path": "/api/v1/share-targets",
        "summary": "Search same-organization share targets"
    },
    "get_tool_approvals": {
        "name": "get_tool_approvals",
        "method": "GET",
        "path": "/api/v1/tool-approvals",
        "summary": "List caller pending tool approval requests"
    },
    "post_tool_approvals_approvalrequestid_approve": {
        "name": "post_tool_approvals_approvalrequestid_approve",
        "method": "POST",
        "path": "/api/v1/tool-approvals/{approvalRequestId}/approve",
        "summary": "Approve a pending caller-owned tool approval request"
    },
    "post_tool_approvals_approvalrequestid_cancel": {
        "name": "post_tool_approvals_approvalrequestid_cancel",
        "method": "POST",
        "path": "/api/v1/tool-approvals/{approvalRequestId}/cancel",
        "summary": "Cancel a pending caller-owned tool approval request"
    },
    "post_tool_approvals_approvalrequestid_reject": {
        "name": "post_tool_approvals_approvalrequestid_reject",
        "method": "POST",
        "path": "/api/v1/tool-approvals/{approvalRequestId}/reject",
        "summary": "Reject a pending caller-owned tool approval request"
    },
    "get_tool_calls": {
        "name": "get_tool_calls",
        "method": "GET",
        "path": "/api/v1/tool-calls",
        "summary": "List recent sanitized tool calls"
    },
    "get_tool_connectors": {
        "name": "get_tool_connectors",
        "method": "GET",
        "path": "/api/v1/tool-connectors",
        "summary": "List imported tool connectors"
    },
    "get_tool_connectors_catalog": {
        "name": "get_tool_connectors_catalog",
        "method": "GET",
        "path": "/api/v1/tool-connectors/catalog",
        "summary": "Inspect supported tool connector types and execution posture"
    },
    "patch_tool_connectors_connectorid": {
        "name": "patch_tool_connectors_connectorid",
        "method": "PATCH",
        "path": "/api/v1/tool-connectors/{connectorId}",
        "summary": "Update imported tool connector activation"
    },
    "patch_tool_connectors_connectorid_auth": {
        "name": "patch_tool_connectors_connectorid_auth",
        "method": "PATCH",
        "path": "/api/v1/tool-connectors/{connectorId}/auth",
        "summary": "Update redacted tool connector auth metadata"
    },
    "post_tool_connectors_connectorid_auth_check": {
        "name": "post_tool_connectors_connectorid_auth_check",
        "method": "POST",
        "path": "/api/v1/tool-connectors/{connectorId}/auth/check",
        "summary": "Check redacted tool connector secret availability"
    },
    "patch_tool_connectors_connectorid_network_policy": {
        "name": "patch_tool_connectors_connectorid_network_policy",
        "method": "PATCH",
        "path": "/api/v1/tool-connectors/{connectorId}/network-policy",
        "summary": "Update tool connector network allowlist policy"
    },
    "get_tool_connectors_connectorid_operations": {
        "name": "get_tool_connectors_connectorid_operations",
        "method": "GET",
        "path": "/api/v1/tool-connectors/{connectorId}/operations",
        "summary": "List imported tool operations"
    },
    "patch_tool_connectors_connectorid_operations_operationid": {
        "name": "patch_tool_connectors_connectorid_operations_operationid",
        "method": "PATCH",
        "path": "/api/v1/tool-connectors/{connectorId}/operations/{operationId}",
        "summary": "Update imported tool operation activation"
    },
    "post_tool_connectors_connectorid_operations_operationid_dispatch": {
        "name": "post_tool_connectors_connectorid_operations_operationid_dispatch",
        "method": "POST",
        "path": "/api/v1/tool-connectors/{connectorId}/operations/{operationId}/dispatch",
        "summary": "Dispatch an imported tool operation through the external worker boundary"
    },
    "post_tool_connectors_connectorid_operations_operationid_dispatch_requests": {
        "name": "post_tool_connectors_connectorid_operations_operationid_dispatch_requests",
        "method": "POST",
        "path": "/api/v1/tool-connectors/{connectorId}/operations/{operationId}/dispatch-requests",
        "summary": "Queue metadata-only imported tool operation dispatch for an external worker"
    },
    "post_tool_connectors_connectorid_operations_operationid_test": {
        "name": "post_tool_connectors_connectorid_operations_operationid_test",
        "method": "POST",
        "path": "/api/v1/tool-connectors/{connectorId}/operations/{operationId}/test",
        "summary": "Dry-run an imported tool operation without network execution"
    },
    "post_tool_operation_dispatch_requests_claim": {
        "name": "post_tool_operation_dispatch_requests_claim",
        "method": "POST",
        "path": "/api/v1/tool-operation-dispatch-requests/claim",
        "summary": "Claim the next queued imported tool operation dispatch request"
    },
    "post_tool_operation_dispatch_requests_expire": {
        "name": "post_tool_operation_dispatch_requests_expire",
        "method": "POST",
        "path": "/api/v1/tool-operation-dispatch-requests/expire",
        "summary": "Expire stale queued or lease-timed-out imported tool operation dispatch requests"
    },
    "post_tool_operation_dispatch_requests_jobid_cancel": {
        "name": "post_tool_operation_dispatch_requests_jobid_cancel",
        "method": "POST",
        "path": "/api/v1/tool-operation-dispatch-requests/{jobId}/cancel",
        "summary": "Cancel a queued or running tool operation dispatch request with sanitized metadata"
    },
    "post_tool_operation_dispatch_requests_jobid_complete": {
        "name": "post_tool_operation_dispatch_requests_jobid_complete",
        "method": "POST",
        "path": "/api/v1/tool-operation-dispatch-requests/{jobId}/complete",
        "summary": "Mark a claimed tool operation dispatch request completed with sanitized worker metadata"
    },
    "post_tool_operation_dispatch_requests_jobid_fail": {
        "name": "post_tool_operation_dispatch_requests_jobid_fail",
        "method": "POST",
        "path": "/api/v1/tool-operation-dispatch-requests/{jobId}/fail",
        "summary": "Mark a claimed tool operation dispatch request failed with sanitized worker metadata"
    },
    "post_tool_operation_dispatch_requests_jobid_payload": {
        "name": "post_tool_operation_dispatch_requests_jobid_payload",
        "method": "POST",
        "path": "/api/v1/tool-operation-dispatch-requests/{jobId}/payload",
        "summary": "Read the managed encrypted payload for an active imported tool operation dispatch lease"
    },
    "post_tool_operation_dispatch_requests_jobid_renew_lease": {
        "name": "post_tool_operation_dispatch_requests_jobid_renew_lease",
        "method": "POST",
        "path": "/api/v1/tool-operation-dispatch-requests/{jobId}/renew-lease",
        "summary": "Renew an active imported tool operation dispatch request lease"
    },
    "get_tools": {
        "name": "get_tools",
        "method": "GET",
        "path": "/api/v1/tools",
        "summary": "List callable tools"
    },
    "post_tools_mcp": {
        "name": "post_tools_mcp",
        "method": "POST",
        "path": "/api/v1/tools/mcp",
        "summary": "Create a Streamable HTTP MCP tool connector from a reviewed manifest"
    },
    "post_tools_openapi": {
        "name": "post_tools_openapi",
        "method": "POST",
        "path": "/api/v1/tools/openapi",
        "summary": "Import an inline OpenAPI tool connector"
    },
    "post_tools_webhook": {
        "name": "post_tools_webhook",
        "method": "POST",
        "path": "/api/v1/tools/webhook",
        "summary": "Create a single-operation webhook tool connector"
    },
    "post_tools_toolid_execute": {
        "name": "post_tools_toolid_execute",
        "method": "POST",
        "path": "/api/v1/tools/{toolId}/execute",
        "summary": "Execute a governed tool for an agent"
    },
    "get_usage_alerts": {
        "name": "get_usage_alerts",
        "method": "GET",
        "path": "/api/v1/usage/alerts",
        "summary": "List quota usage alerts"
    },
    "get_usage_events": {
        "name": "get_usage_events",
        "method": "GET",
        "path": "/api/v1/usage/events",
        "summary": "List organization usage events"
    },
    "get_usage_events_csv": {
        "name": "get_usage_events_csv",
        "method": "GET",
        "path": "/api/v1/usage/events.csv",
        "summary": "Export organization usage events as CSV"
    },
    "get_usage_summary": {
        "name": "get_usage_summary",
        "method": "GET",
        "path": "/api/v1/usage/summary",
        "summary": "Summarize organization usage"
    },
    "get_users": {
        "name": "get_users",
        "method": "GET",
        "path": "/api/v1/users",
        "summary": "List organization users"
    },
    "post_users_userid_disable": {
        "name": "post_users_userid_disable",
        "method": "POST",
        "path": "/api/v1/users/{userId}/disable",
        "summary": "Disable a user and revoke user credentials"
    },
    "post_users_userid_local_password": {
        "name": "post_users_userid_local_password",
        "method": "POST",
        "path": "/api/v1/users/{userId}/local-password",
        "summary": "Set or reset a user local password for SSO fallback"
    },
    "patch_users_userid_role": {
        "name": "patch_users_userid_role",
        "method": "PATCH",
        "path": "/api/v1/users/{userId}/role",
        "summary": "Promote or demote a local or SSO-provisioned user role"
    },
    "delete_voice_artifacts_artifactid": {
        "name": "delete_voice_artifacts_artifactid",
        "method": "DELETE",
        "path": "/api/v1/voice-artifacts/{artifactId}",
        "summary": "Delete an authorized generated voice artifact"
    },
    "get_voice_artifacts_artifactid": {
        "name": "get_voice_artifacts_artifactid",
        "method": "GET",
        "path": "/api/v1/voice-artifacts/{artifactId}",
        "summary": "Read an authorized generated voice artifact"
    },
    "post_voice_transcriptions": {
        "name": "post_voice_transcriptions",
        "method": "POST",
        "path": "/api/v1/voice/transcriptions",
        "summary": "Transcribe bounded audio input"
    },
    "get_voices": {
        "name": "get_voices",
        "method": "GET",
        "path": "/api/v1/voices",
        "summary": "List voice profiles"
    },
    "post_voices": {
        "name": "post_voices",
        "method": "POST",
        "path": "/api/v1/voices",
        "summary": "Create a voice profile"
    },
    "post_voices_sync": {
        "name": "post_voices_sync",
        "method": "POST",
        "path": "/api/v1/voices/sync",
        "summary": "Sync voice profiles from the configured provider catalog"
    },
    "post_voices_voiceprofileid_preview": {
        "name": "post_voices_voiceprofileid_preview",
        "method": "POST",
        "path": "/api/v1/voices/{voiceProfileId}/preview",
        "summary": "Preview a voice profile"
    },
    "get_webhook_deliveries": {
        "name": "get_webhook_deliveries",
        "method": "GET",
        "path": "/api/v1/webhook-deliveries",
        "summary": "List recent webhook delivery logs"
    },
    "post_webhook_deliveries_retry_due": {
        "name": "post_webhook_deliveries_retry_due",
        "method": "POST",
        "path": "/api/v1/webhook-deliveries/retry-due",
        "summary": "Retry due failed webhook deliveries"
    },
    "get_webhooks": {
        "name": "get_webhooks",
        "method": "GET",
        "path": "/api/v1/webhooks",
        "summary": "List webhook subscriptions"
    },
    "post_webhooks": {
        "name": "post_webhooks",
        "method": "POST",
        "path": "/api/v1/webhooks",
        "summary": "Create a webhook subscription"
    },
    "post_webhooks_bulk_disable": {
        "name": "post_webhooks_bulk_disable",
        "method": "POST",
        "path": "/api/v1/webhooks/bulk-disable",
        "summary": "Disable multiple webhook subscriptions"
    },
    "get_webhooks_webhookid_deliveries": {
        "name": "get_webhooks_webhookid_deliveries",
        "method": "GET",
        "path": "/api/v1/webhooks/{webhookId}/deliveries",
        "summary": "List webhook delivery logs for a subscription"
    },
    "post_webhooks_webhookid_disable": {
        "name": "post_webhooks_webhookid_disable",
        "method": "POST",
        "path": "/api/v1/webhooks/{webhookId}/disable",
        "summary": "Disable a webhook subscription"
    },
    "post_webhooks_webhookid_test": {
        "name": "post_webhooks_webhookid_test",
        "method": "POST",
        "path": "/api/v1/webhooks/{webhookId}/test",
        "summary": "Send a signed webhook test delivery"
    },
    "post_workflow_runs_workflowrunid_approve": {
        "name": "post_workflow_runs_workflowrunid_approve",
        "method": "POST",
        "path": "/api/v1/workflow-runs/{workflowRunId}/approve",
        "summary": "Approve a waiting workflow run"
    },
    "post_workflow_runs_workflowrunid_resume": {
        "name": "post_workflow_runs_workflowrunid_resume",
        "method": "POST",
        "path": "/api/v1/workflow-runs/{workflowRunId}/resume",
        "summary": "Resume a workflow run waiting for a linked model run"
    },
    "get_workflow_templates": {
        "name": "get_workflow_templates",
        "method": "GET",
        "path": "/api/v1/workflow-templates",
        "summary": "List safe workflow templates"
    },
    "post_workflow_templates_templateid_create": {
        "name": "post_workflow_templates_templateid_create",
        "method": "POST",
        "path": "/api/v1/workflow-templates/{templateId}/create",
        "summary": "Create a workflow definition from a safe template"
    },
    "get_workflows": {
        "name": "get_workflows",
        "method": "GET",
        "path": "/api/v1/workflows",
        "summary": "List workflow definitions"
    },
    "post_workflows": {
        "name": "post_workflows",
        "method": "POST",
        "path": "/api/v1/workflows",
        "summary": "Create a safe workflow definition"
    },
    "post_workflows_schedules_run_due": {
        "name": "post_workflows_schedules_run_due",
        "method": "POST",
        "path": "/api/v1/workflows/schedules/run-due",
        "summary": "Start due scheduled workflows visible to the caller"
    },
    "get_workflows_workflowid_runs": {
        "name": "get_workflows_workflowid_runs",
        "method": "GET",
        "path": "/api/v1/workflows/{workflowId}/runs",
        "summary": "List workflow runs"
    },
    "post_workflows_workflowid_runs": {
        "name": "post_workflows_workflowid_runs",
        "method": "POST",
        "path": "/api/v1/workflows/{workflowId}/runs",
        "summary": "Start a workflow run"
    },
    "get_workspaces": {
        "name": "get_workspaces",
        "method": "GET",
        "path": "/api/v1/workspaces",
        "summary": "List workspaces visible to the caller"
    },
    "post_workspaces": {
        "name": "post_workspaces",
        "method": "POST",
        "path": "/api/v1/workspaces",
        "summary": "Create a workspace"
    },
    "post_workspaces_workspaceid_archive": {
        "name": "post_workspaces_workspaceid_archive",
        "method": "POST",
        "path": "/api/v1/workspaces/{workspaceId}/archive",
        "summary": "Archive a workspace"
    },
    "get_workspaces_workspaceid_export": {
        "name": "get_workspaces_workspaceid_export",
        "method": "GET",
        "path": "/api/v1/workspaces/{workspaceId}/export",
        "summary": "Export a sanitized workspace data inventory"
    }
}
